### Import libraries and set project paths

In [2]:
from pathlib import Path
import random

import numpy as np
import pandas as pd

# -------------------------------------------------
# Reproducibility
# -------------------------------------------------
SEED = 42

random.seed(SEED)
np.random.seed(SEED)

# -------------------------------------------------
# Project paths
# -------------------------------------------------
PROJECT_ROOT = Path.cwd().parent

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
STAGING_DATA_DIR = PROJECT_ROOT / "data" / "staging"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

# Make sure the folders exist
RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
STAGING_DATA_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Raw data folder:", RAW_DATA_DIR)

Project root: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics
Raw data folder: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw

### Generate plans.csv

In [3]:
# -------------------------------------------------
# Generate subscription plans
# -------------------------------------------------

plans_data = [
    {
        "plan_id": "P001",
        "plan_name": "Free",
        "monthly_price": 0.00,
        "annual_price": 0.00,
        "max_users": 1,
        "storage_limit_gb": 5,
        "plan_status": "Active"
    },
    {
        "plan_id": "P002",
        "plan_name": "Pro",
        "monthly_price": 15.00,
        "annual_price": 144.00,
        "max_users": 10,
        "storage_limit_gb": 100,
        "plan_status": "Active"
    },
    {
        "plan_id": "P003",
        "plan_name": "Business",
        "monthly_price": 30.00,
        "annual_price": 288.00,
        "max_users": 100,
        "storage_limit_gb": 1000,
        "plan_status": "Active"
    }
]

plans_df = pd.DataFrame(plans_data)

plans_df

,plan_id,plan_name,monthly_price,annual_price,max_users,storage_limit_gb,plan_status
0,P001,Free,0.0,0.0,1,5,Active
1,P002,Pro,15.0,144.0,10,100,Active
2,P003,Business,30.0,288.0,100,1000,Active

### Save it as raw data

In [4]:
# -------------------------------------------------
# Save plans raw dataset
# -------------------------------------------------

plans_file = RAW_DATA_DIR / "plans.csv"

plans_df.to_csv(
    plans_file,
    index=False
)

print(f"Saved: {plans_file}")
print(f"Rows: {len(plans_df):,}")

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\plans.csv
Rows: 3

### Generate features.csv

In [5]:
# -------------------------------------------------
# Generate product features
# -------------------------------------------------

features_data = [
    {
        "feature_id": "F001",
        "feature_name": "Project Creation",
        "feature_category": "Core",
        "minimum_plan": "Free",
        "feature_status": "Active",
        "launch_date": "2024-01-15"
    },
    {
        "feature_id": "F002",
        "feature_name": "Task Management",
        "feature_category": "Core",
        "minimum_plan": "Free",
        "feature_status": "Active",
        "launch_date": "2024-01-15"
    },
    {
        "feature_id": "F003",
        "feature_name": "File Sharing",
        "feature_category": "Collaboration",
        "minimum_plan": "Free",
        "feature_status": "Active",
        "launch_date": "2024-03-01"
    },
    {
        "feature_id": "F004",
        "feature_name": "Team Collaboration",
        "feature_category": "Collaboration",
        "minimum_plan": "Pro",
        "feature_status": "Active",
        "launch_date": "2024-04-10"
    },
    {
        "feature_id": "F005",
        "feature_name": "Calendar Integration",
        "feature_category": "Integration",
        "minimum_plan": "Pro",
        "feature_status": "Active",
        "launch_date": "2024-05-20"
    },
    {
        "feature_id": "F006",
        "feature_name": "Workflow Automation",
        "feature_category": "Automation",
        "minimum_plan": "Pro",
        "feature_status": "Active",
        "launch_date": "2024-07-01"
    },
    {
        "feature_id": "F007",
        "feature_name": "Dashboard Reporting",
        "feature_category": "Reporting",
        "minimum_plan": "Pro",
        "feature_status": "Active",
        "launch_date": "2024-08-15"
    },
    {
        "feature_id": "F008",
        "feature_name": "Advanced Analytics",
        "feature_category": "Reporting",
        "minimum_plan": "Business",
        "feature_status": "Active",
        "launch_date": "2024-10-01"
    },
    {
        "feature_id": "F009",
        "feature_name": "Role Based Access",
        "feature_category": "Security",
        "minimum_plan": "Business",
        "feature_status": "Active",
        "launch_date": "2024-11-15"
    },
    {
        "feature_id": "F010",
        "feature_name": "Audit Logs",
        "feature_category": "Security",
        "minimum_plan": "Business",
        "feature_status": "Active",
        "launch_date": "2025-01-10"
    },
    {
        "feature_id": "F011",
        "feature_name": "API Access",
        "feature_category": "Integration",
        "minimum_plan": "Business",
        "feature_status": "Active",
        "launch_date": "2025-03-01"
    },
    {
        "feature_id": "F012",
        "feature_name": "AI Task Assistant",
        "feature_category": "AI",
        "minimum_plan": "Pro",
        "feature_status": "Beta",
        "launch_date": "2026-03-15"
    }
]

features_df = pd.DataFrame(features_data)

features_df["launch_date"] = pd.to_datetime(
    features_df["launch_date"]
).dt.date

features_df

,feature_id,feature_name,feature_category,minimum_plan,feature_status,launch_date
0,F001,Project Creation,Core,Free,Active,2024-01-15
1,F002,Task Management,Core,Free,Active,2024-01-15
2,F003,File Sharing,Collaboration,Free,Active,2024-03-01
3,F004,Team Collaboration,Collaboration,Pro,Active,2024-04-10
4,F005,Calendar Integration,Integration,Pro,Active,2024-05-20
5,F006,Workflow Automation,Automation,Pro,Active,2024-07-01
6,F007,Dashboard Reporting,Reporting,Pro,Active,2024-08-15
7,F008,Advanced Analytics,Reporting,Business,Active,2024-10-01
8,F009,Role Based Access,Security,Business,Active,2024-11-15
9,F010,Audit Logs,Security,Business,Active,2025-01-10
10,F011,API Access,Integration,Business,Active,2025-03-01
11,F012,AI Task Assistant,AI,Pro,Beta,2026-03-15

### Save the file

In [6]:
# -------------------------------------------------
# Save features raw dataset
# -------------------------------------------------

features_file = RAW_DATA_DIR / "features.csv"

features_df.to_csv(
    features_file,
    index=False
)

print(f"Saved: {features_file}")
print(f"Rows: {len(features_df):,}")

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\features.csv
Rows: 12

### Generate experiments.csv

In [7]:
# -------------------------------------------------
# Generate product experiments
# -------------------------------------------------

experiments_data = [
    {
        "experiment_id": "EXP001",
        "experiment_name": "Simplified Onboarding Flow",
        "experiment_description": (
            "Tests whether a shorter guided onboarding flow "
            "improves user activation."
        ),
        "primary_metric": "Activation Rate",
        "start_date": "2026-04-01",
        "end_date": "2026-05-31",
        "experiment_status": "Completed"
    },
    {
        "experiment_id": "EXP002",
        "experiment_name": "Upgrade CTA Placement",
        "experiment_description": (
            "Tests whether moving the upgrade call-to-action "
            "increases paid conversion."
        ),
        "primary_metric": "Paid Conversion Rate",
        "start_date": "2026-06-15",
        "end_date": "2026-07-31",
        "experiment_status": "Completed"
    },
    {
        "experiment_id": "EXP003",
        "experiment_name": "AI Assistant Recommendation",
        "experiment_description": (
            "Tests whether recommending the AI Task Assistant "
            "increases feature adoption."
        ),
        "primary_metric": "Feature Adoption Rate",
        "start_date": "2026-08-01",
        "end_date": None,
        "experiment_status": "Running"
    }
]

experiments_df = pd.DataFrame(experiments_data)

experiments_df["start_date"] = pd.to_datetime(
    experiments_df["start_date"]
).dt.date

experiments_df["end_date"] = pd.to_datetime(
    experiments_df["end_date"],
    errors="coerce"
).dt.date

experiments_df

,experiment_id,experiment_name,experiment_description,primary_metric,start_date,end_date,experiment_status
0,EXP001,Simplified Onboarding Flow,Tests whether a shorter guided onboarding flow...,Activation Rate,2026-04-01,2026-05-31,Completed
1,EXP002,Upgrade CTA Placement,Tests whether moving the upgrade call-to-actio...,Paid Conversion Rate,2026-06-15,2026-07-31,Completed
2,EXP003,AI Assistant Recommendation,Tests whether recommending the AI Task Assista...,Feature Adoption Rate,2026-08-01,NaT,Running

### Save the raw table

In [8]:
# -------------------------------------------------
# Save experiments raw dataset
# -------------------------------------------------

experiments_file = RAW_DATA_DIR / "experiments.csv"

experiments_df.to_csv(
    experiments_file,
    index=False
)

print(f"Saved: {experiments_file}")
print(f"Rows: {len(experiments_df):,}")

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\experiments.csv
Rows: 3

### Generate organizations.csv

In [9]:
# -------------------------------------------------
# Generate organizations
# -------------------------------------------------

N_ORGANIZATIONS = 8_000

industries = [
    "Technology",
    "Healthcare",
    "Finance",
    "Education",
    "Retail",
    "Manufacturing",
    "Professional Services",
    "Media",
    "Nonprofit",
    "Other"
]

company_sizes = [
    "Small",
    "Medium",
    "Enterprise"
]

countries = [
    "United States",
    "Canada",
    "United Kingdom",
    "Germany",
    "India",
    "Australia",
    "France",
    "Netherlands"
]

organization_statuses = [
    "Active",
    "Suspended",
    "Closed"
]

org_ids = [
    f"ORG{str(i).zfill(5)}"
    for i in range(1, N_ORGANIZATIONS + 1)
]

organization_names = [
    f"NovaClient_{str(i).zfill(5)}"
    for i in range(1, N_ORGANIZATIONS + 1)
]

created_dates = pd.to_datetime(
    np.random.choice(
        pd.date_range(
            start="2023-01-01",
            end="2026-08-31",
            freq="D"
        ),
        size=N_ORGANIZATIONS
    )
)

organizations_df = pd.DataFrame({
    "organization_id": org_ids,
    "organization_name": organization_names,
    "industry": np.random.choice(
        industries,
        size=N_ORGANIZATIONS,
        p=[0.20, 0.12, 0.10, 0.10, 0.12, 0.08, 0.12, 0.06, 0.04, 0.06]
    ),
    "company_size": np.random.choice(
        company_sizes,
        size=N_ORGANIZATIONS,
        p=[0.60, 0.30, 0.10]
    ),
    "country": np.random.choice(
        countries,
        size=N_ORGANIZATIONS,
        p=[0.50, 0.08, 0.10, 0.07, 0.10, 0.05, 0.05, 0.05]
    ),
    "created_timestamp": created_dates,
    "organization_status": np.random.choice(
        organization_statuses,
        size=N_ORGANIZATIONS,
        p=[0.94, 0.03, 0.03]
    )
})

organizations_df.head()

,organization_id,organization_name,industry,company_size,country,created_timestamp,organization_status
0,ORG00001,NovaClient_00001,Other,Small,United States,2026-01-31,Active
1,ORG00002,NovaClient_00002,Healthcare,Enterprise,Netherlands,2025-05-10,Active
2,ORG00003,NovaClient_00003,Manufacturing,Small,India,2026-07-18,Active
3,ORG00004,NovaClient_00004,Technology,Medium,India,2026-02-04,Active
4,ORG00005,NovaClient_00005,Technology,Small,United States,2025-12-31,Active

### Validate the generated data

In [10]:
print("Rows:", len(organizations_df))
print()
print("Company size distribution:")
print(
    organizations_df["company_size"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)
print()
print("Organization status distribution:")
print(
    organizations_df["organization_status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Rows: 8000

Company size distribution:
company_size
Small         58.82
Medium        30.84
Enterprise    10.34
Name: proportion, dtype: float64

Organization status distribution:
organization_status
Active       94.15
Suspended     2.99
Closed        2.86
Name: proportion, dtype: float64

### Save organizations.csv

In [11]:
# -------------------------------------------------
# Save organizations raw dataset
# -------------------------------------------------

organizations_file = RAW_DATA_DIR / "organizations.csv"

organizations_df.to_csv(
    organizations_file,
    index=False
)

print(f"Saved: {organizations_file}")
print(f"Rows: {len(organizations_df):,}")

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\organizations.csv
Rows: 8,000

### Generate users.csv

In [12]:
# -------------------------------------------------
# Generate users
# -------------------------------------------------

N_USERS = 100_000

first_names = [
    "Aarav", "Aiden", "Amelia", "Arjun", "Ava",
    "Benjamin", "Charlotte", "Daniel", "Emma", "Ethan",
    "Isabella", "James", "Liam", "Lucas", "Mia",
    "Noah", "Olivia", "Sophia", "William", "Zoe"
]

last_names = [
    "Anderson", "Brown", "Davis", "Garcia", "Johnson",
    "Jones", "Khan", "Lee", "Martin", "Miller",
    "Patel", "Rodriguez", "Sharma", "Singh", "Smith",
    "Taylor", "Thomas", "Walker", "White", "Wilson"
]

user_countries = [
    "United States",
    "Canada",
    "United Kingdom",
    "Germany",
    "India",
    "Australia",
    "France",
    "Netherlands"
]

signup_platforms = [
    "Web",
    "iOS",
    "Android"
]

account_statuses = [
    "Active",
    "Suspended",
    "Deleted"
]

acquisition_channels = [
    "Organic Search",
    "Paid Search",
    "Social",
    "Referral",
    "Partner",
    "Direct",
    "Email"
]

user_ids = [
    f"U{str(i).zfill(6)}"
    for i in range(1, N_USERS + 1)
]

selected_first_names = np.random.choice(
    first_names,
    size=N_USERS
)

selected_last_names = np.random.choice(
    last_names,
    size=N_USERS
)

emails = [
    f"{first.lower()}.{last.lower()}.{i}@example.com"
    for i, (first, last) in enumerate(
        zip(selected_first_names, selected_last_names),
        start=1
    )
]

registration_dates = pd.to_datetime(
    np.random.choice(
        pd.date_range(
            start="2024-01-01",
            end="2026-08-31",
            freq="D"
        ),
        size=N_USERS
    )
)

# About 35% of users belong to an organization
organization_assignment = np.where(
    np.random.random(N_USERS) < 0.35,
    np.random.choice(
        organizations_df["organization_id"],
        size=N_USERS
    ),
    None
)

users_df = pd.DataFrame({
    "user_id": user_ids,
    "organization_id": organization_assignment,
    "first_name": selected_first_names,
    "last_name": selected_last_names,
    "email": emails,
    "country": np.random.choice(
        user_countries,
        size=N_USERS,
        p=[0.50, 0.08, 0.10, 0.07, 0.10, 0.05, 0.05, 0.05]
    ),
    "registration_timestamp": registration_dates,
    "signup_platform": np.random.choice(
        signup_platforms,
        size=N_USERS,
        p=[0.62, 0.18, 0.20]
    ),
    "account_status": np.random.choice(
        account_statuses,
        size=N_USERS,
        p=[0.96, 0.02, 0.02]
    ),
    "acquisition_channel": np.random.choice(
        acquisition_channels,
        size=N_USERS,
        p=[0.26, 0.20, 0.15, 0.12, 0.08, 0.12, 0.07]
    )
})

users_df.head()

,user_id,organization_id,first_name,last_name,email,country,registration_timestamp,signup_platform,account_status,acquisition_channel
0,U000001,ORG04951,Arjun,Singh,arjun.singh.1@example.com,Canada,2024-09-11,Web,Active,Paid Search
1,U000002,ORG00273,Isabella,Rodriguez,isabella.rodriguez.2@example.com,Canada,2025-05-26,iOS,Active,Direct
2,U000003,ORG03994,Aarav,Martin,aarav.martin.3@example.com,Netherlands,2026-01-09,Web,Deleted,Referral
3,U000004,NaN,Ethan,Jones,ethan.jones.4@example.com,United States,2026-02-09,Web,Active,Paid Search
4,U000005,ORG02996,Arjun,Rodriguez,arjun.rodriguez.5@example.com,Germany,2025-09-26,iOS,Active,Partner

### Validate the user data

In [13]:
print("Rows:", len(users_df))
print()

print("Organization membership:")
print(
    users_df["organization_id"]
    .notna()
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)
print()

print("Signup platform distribution:")
print(
    users_df["signup_platform"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)
print()

print("Acquisition channel distribution:")
print(
    users_df["acquisition_channel"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Rows: 100000

Organization membership:
organization_id
False    64.9
True     35.1
Name: proportion, dtype: float64

Signup platform distribution:
signup_platform
Web        61.89
Android    20.17
iOS        17.94
Name: proportion, dtype: float64

Acquisition channel distribution:
acquisition_channel
Organic Search    26.04
Paid Search       19.91
Social            15.07
Direct            11.98
Referral          11.96
Partner            7.96
Email              7.08
Name: proportion, dtype: float64

### Check uniqueness

In [14]:
print(
    "Unique user IDs:",
    users_df["user_id"].nunique()
)

print(
    "Unique emails:",
    users_df["email"].nunique()
)

Unique user IDs: 100000
Unique emails: 100000

### Save users.csv

In [15]:
# -------------------------------------------------
# Save users raw dataset
# -------------------------------------------------

users_file = RAW_DATA_DIR / "users.csv"

users_df.to_csv(
    users_file,
    index=False
)

print(f"Saved: {users_file}")
print(f"Rows: {len(users_df):,}")

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\users.csv
Rows: 100,000

## Add controlled data-quality problems

### Create the imperfect raw copy

In [16]:
# -------------------------------------------------
# Create raw users dataset with controlled
# data-quality issues
# -------------------------------------------------

users_raw_df = users_df.copy()

# Separate random generator for reproducible DQ issues
dq_rng = np.random.default_rng(SEED + 100)

# Shuffle row indexes so each issue can be placed
# on a different set of users
available_indexes = np.arange(len(users_raw_df))
dq_rng.shuffle(available_indexes)

cursor = 0

def get_indexes(n):
    global cursor
    selected = available_indexes[cursor:cursor + n]
    cursor += n
    return selected

### Introduce the issues

In [17]:
# -------------------------------------------------
# Inject realistic raw data-quality issues
# -------------------------------------------------

# 1. Invalid email formats
invalid_email_idx = get_indexes(120)
users_raw_df.loc[invalid_email_idx, "email"] = (
    "invalid_email_" +
    users_raw_df.loc[invalid_email_idx, "user_id"]
)

# 2. Missing countries
missing_country_idx = get_indexes(100)
users_raw_df.loc[missing_country_idx, "country"] = None

# 3. Invalid signup platforms
invalid_platform_idx = get_indexes(80)
users_raw_df.loc[
    invalid_platform_idx,
    "signup_platform"
] = "DesktopApp"

# 4. Invalid account statuses
invalid_status_idx = get_indexes(60)
users_raw_df.loc[
    invalid_status_idx,
    "account_status"
] = "Unknown"

# 5. Future registration timestamps
future_date_idx = get_indexes(50)
users_raw_df.loc[
    future_date_idx,
    "registration_timestamp"
] = pd.Timestamp("2027-01-15")

# 6. Broken organization foreign keys
broken_org_idx = get_indexes(50)
users_raw_df.loc[
    broken_org_idx,
    "organization_id"
] = "ORG99999"

print("Controlled data-quality issues added.")

Controlled data-quality issues added.

### Add duplicate records

In [18]:
# -------------------------------------------------
# Add duplicate user records
# -------------------------------------------------

duplicate_count = 75

duplicate_rows = users_raw_df.sample(
    n=duplicate_count,
    random_state=SEED
).copy()

users_raw_df = pd.concat(
    [users_raw_df, duplicate_rows],
    ignore_index=True
)

print("Original clean rows:", len(users_df))
print("Raw rows after duplicates:", len(users_raw_df))

Original clean rows: 100000
Raw rows after duplicates: 100075

### Quick verification

In [19]:
# -------------------------------------------------
# Verify injected data-quality issues
# -------------------------------------------------

valid_platforms = ["Web", "iOS", "Android"]

valid_statuses = [
    "Active",
    "Suspended",
    "Deleted"
]

valid_org_ids = set(
    organizations_df["organization_id"]
)

print(
    "Duplicate user IDs:",
    users_raw_df["user_id"].duplicated().sum()
)

print(
    "Missing countries:",
    users_raw_df["country"].isna().sum()
)

print(
    "Invalid platforms:",
    (~users_raw_df["signup_platform"]
        .isin(valid_platforms)).sum()
)

print(
    "Invalid account statuses:",
    (~users_raw_df["account_status"]
        .isin(valid_statuses)).sum()
)

print(
    "Future registration dates:",
    (
        users_raw_df["registration_timestamp"]
        > pd.Timestamp("2026-09-01")
    ).sum()
)

print(
    "Broken organization references:",
    (
        users_raw_df["organization_id"].notna()
        &
        ~users_raw_df["organization_id"].isin(valid_org_ids)
    ).sum()
)

Duplicate user IDs: 75
Missing countries: 100
Invalid platforms: 80
Invalid account statuses: 61
Future registration dates: 50
Broken organization references: 50

### Replace raw users.csv

In [20]:
# -------------------------------------------------
# Save imperfect raw users source
# -------------------------------------------------

users_raw_file = RAW_DATA_DIR / "users.csv"

users_raw_df.to_csv(
    users_raw_file,
    index=False
)

print(f"Saved raw users: {users_raw_file}")
print(f"Rows: {len(users_raw_df):,}")

Saved raw users: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\users.csv
Rows: 100,075

### Generate subscriptions.csv

In [21]:
# -------------------------------------------------
# Generate user-level subscriptions
# -------------------------------------------------

CURRENT_DATE = pd.Timestamp("2026-08-31")

N_USER_SUBSCRIPTIONS = 66_000

subscription_rng = np.random.default_rng(SEED + 200)

# Select users who will have a subscription
selected_user_indexes = subscription_rng.choice(
    users_df.index,
    size=N_USER_SUBSCRIPTIONS,
    replace=False
)

selected_users = users_df.loc[
    selected_user_indexes,
    ["user_id", "registration_timestamp"]
].reset_index(drop=True)

user_subscription_rows = []

for i, row in selected_users.iterrows():

    user_id = row["user_id"]
    registration_date = pd.Timestamp(
        row["registration_timestamp"]
    )

    # Subscription cannot start before registration
    max_days = max(
        (CURRENT_DATE - registration_date).days,
        0
    )

    start_offset = (
        subscription_rng.integers(0, max_days + 1)
        if max_days > 0
        else 0
    )

    start_date = (
        registration_date
        + pd.Timedelta(days=int(start_offset))
    ).normalize()

    # Individual-user plan mix
    plan_id = subscription_rng.choice(
        ["P001", "P002", "P003"],
        p=[0.48, 0.47, 0.05]
    )

    billing_cycle = subscription_rng.choice(
        ["Monthly", "Annual"],
        p=[0.72, 0.28]
    )

    status = subscription_rng.choice(
        ["Active", "Cancelled", "Expired", "Trial"],
        p=[0.64, 0.18, 0.10, 0.08]
    )

    end_date = pd.NaT
    cancellation_reason = None

    if status in ["Cancelled", "Expired"]:

        available_days = max(
            (CURRENT_DATE - start_date).days,
            1
        )

        end_offset = subscription_rng.integers(
            1,
            available_days + 1
        )

        end_date = (
            start_date
            + pd.Timedelta(days=int(end_offset))
        )

        cancellation_reason = (
            subscription_rng.choice(
                [
                    "Too Expensive",
                    "Low Usage",
                    "Missing Features",
                    "Switched Competitor",
                    "Temporary Need",
                    "Other"
                ]
            )
            if status == "Cancelled"
            else None
        )

    auto_renew_flag = bool(
        subscription_rng.random()
        <
        (
            0.88 if status == "Active"
            else 0.65 if status == "Trial"
            else 0.05
        )
    )

    user_subscription_rows.append({
        "user_id": user_id,
        "organization_id": None,
        "plan_id": plan_id,
        "subscription_start_date": start_date.date(),
        "subscription_end_date": (
            end_date.date()
            if pd.notna(end_date)
            else None
        ),
        "billing_cycle": billing_cycle,
        "subscription_status": status,
        "auto_renew_flag": auto_renew_flag,
        "cancellation_reason": cancellation_reason
    })

user_subscriptions_df = pd.DataFrame(
    user_subscription_rows
)

user_subscriptions_df.head()

,user_id,organization_id,plan_id,subscription_start_date,subscription_end_date,billing_cycle,subscription_status,auto_renew_flag,cancellation_reason
0,U029960,None,P002,2026-08-01,None,Annual,Active,True,NaN
1,U087945,None,P001,2025-07-01,None,Monthly,Active,True,NaN
2,U004125,None,P002,2026-05-24,None,Monthly,Active,True,NaN
3,U073027,None,P002,2026-07-12,None,Monthly,Active,True,NaN
4,U085250,None,P002,2025-12-10,None,Annual,Active,True,NaN

### Generate organization subscriptions

In [22]:
# -------------------------------------------------
# Generate organization-level subscriptions
# -------------------------------------------------

N_ORG_SUBSCRIPTIONS = 6_000

selected_org_indexes = subscription_rng.choice(
    organizations_df.index,
    size=N_ORG_SUBSCRIPTIONS,
    replace=False
)

selected_orgs = organizations_df.loc[
    selected_org_indexes,
    ["organization_id", "created_timestamp"]
].reset_index(drop=True)

org_subscription_rows = []

for i, row in selected_orgs.iterrows():

    organization_id = row["organization_id"]

    created_date = pd.Timestamp(
        row["created_timestamp"]
    )

    max_days = max(
        (CURRENT_DATE - created_date).days,
        0
    )

    start_offset = (
        subscription_rng.integers(0, max_days + 1)
        if max_days > 0
        else 0
    )

    start_date = (
        created_date
        + pd.Timedelta(days=int(start_offset))
    ).normalize()

    # Organizations are primarily Business customers
    plan_id = subscription_rng.choice(
        ["P002", "P003"],
        p=[0.20, 0.80]
    )

    billing_cycle = subscription_rng.choice(
        ["Monthly", "Annual"],
        p=[0.40, 0.60]
    )

    status = subscription_rng.choice(
        ["Active", "Cancelled", "Expired", "Trial"],
        p=[0.72, 0.14, 0.08, 0.06]
    )

    end_date = pd.NaT
    cancellation_reason = None

    if status in ["Cancelled", "Expired"]:

        available_days = max(
            (CURRENT_DATE - start_date).days,
            1
        )

        end_offset = subscription_rng.integers(
            1,
            available_days + 1
        )

        end_date = (
            start_date
            + pd.Timedelta(days=int(end_offset))
        )

        cancellation_reason = (
            subscription_rng.choice(
                [
                    "Too Expensive",
                    "Low Usage",
                    "Missing Features",
                    "Switched Competitor",
                    "Contract Ended",
                    "Other"
                ]
            )
            if status == "Cancelled"
            else None
        )

    auto_renew_flag = bool(
        subscription_rng.random()
        <
        (
            0.92 if status == "Active"
            else 0.70 if status == "Trial"
            else 0.05
        )
    )

    org_subscription_rows.append({
        "user_id": None,
        "organization_id": organization_id,
        "plan_id": plan_id,
        "subscription_start_date": start_date.date(),
        "subscription_end_date": (
            end_date.date()
            if pd.notna(end_date)
            else None
        ),
        "billing_cycle": billing_cycle,
        "subscription_status": status,
        "auto_renew_flag": auto_renew_flag,
        "cancellation_reason": cancellation_reason
    })

org_subscriptions_df = pd.DataFrame(
    org_subscription_rows
)

org_subscriptions_df.head()

,user_id,organization_id,plan_id,subscription_start_date,subscription_end_date,billing_cycle,subscription_status,auto_renew_flag,cancellation_reason
0,None,ORG02201,P003,2024-01-16,None,Annual,Active,True,NaN
1,None,ORG02663,P003,2026-07-25,None,Annual,Active,True,NaN
2,None,ORG00667,P003,2025-11-05,None,Monthly,Active,True,NaN
3,None,ORG07710,P003,2026-07-05,2026-08-12,Annual,Cancelled,False,Other
4,None,ORG00182,P003,2025-05-02,2026-04-10,Annual,Expired,False,NaN

### Combine them and create the subscription PK

In [23]:
# -------------------------------------------------
# Combine user and organization subscriptions
# -------------------------------------------------

subscriptions_df = pd.concat(
    [
        user_subscriptions_df,
        org_subscriptions_df
    ],
    ignore_index=True
)

subscriptions_df.insert(
    0,
    "subscription_id",
    [
        f"SUB{str(i).zfill(6)}"
        for i in range(
            1,
            len(subscriptions_df) + 1
        )
    ]
)

subscriptions_df.head()

,subscription_id,user_id,organization_id,plan_id,subscription_start_date,subscription_end_date,billing_cycle,subscription_status,auto_renew_flag,cancellation_reason
0,SUB000001,U029960,None,P002,2026-08-01,None,Annual,Active,True,NaN
1,SUB000002,U087945,None,P001,2025-07-01,None,Monthly,Active,True,NaN
2,SUB000003,U004125,None,P002,2026-05-24,None,Monthly,Active,True,NaN
3,SUB000004,U073027,None,P002,2026-07-12,None,Monthly,Active,True,NaN
4,SUB000005,U085250,None,P002,2025-12-10,None,Annual,Active,True,NaN

### Validate our business rules

In [24]:
# -------------------------------------------------
# Validate subscription generation
# -------------------------------------------------

print(
    "Total subscriptions:",
    len(subscriptions_df)
)

print()

print("Plan distribution:")
print(
    subscriptions_df["plan_id"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print()

print("Subscription status:")
print(
    subscriptions_df["subscription_status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print()

print(
    "Rows with BOTH user and organization:",
    (
        subscriptions_df["user_id"].notna()
        &
        subscriptions_df["organization_id"].notna()
    ).sum()
)

print(
    "Rows with NEITHER user nor organization:",
    (
        subscriptions_df["user_id"].isna()
        &
        subscriptions_df["organization_id"].isna()
    ).sum()
)

print(
    "Unique subscription IDs:",
    subscriptions_df["subscription_id"].nunique()
)

Total subscriptions: 72000

Plan distribution:
plan_id
P002    45.03
P001    43.74
P003    11.23
Name: proportion, dtype: float64

Subscription status:
subscription_status
Active       64.72
Cancelled    17.55
Expired       9.90
Trial         7.83
Name: proportion, dtype: float64

Rows with BOTH user and organization: 0
Rows with NEITHER user nor organization: 0
Unique subscription IDs: 72000

### Check subscription dates

In [25]:
# -------------------------------------------------
# Validate subscription date logic
# -------------------------------------------------

subscription_dates_check = subscriptions_df[
    subscriptions_df["subscription_end_date"].notna()
].copy()

subscription_dates_check[
    "subscription_start_date"
] = pd.to_datetime(
    subscription_dates_check[
        "subscription_start_date"
    ]
)

subscription_dates_check[
    "subscription_end_date"
] = pd.to_datetime(
    subscription_dates_check[
        "subscription_end_date"
    ]
)

invalid_subscription_dates = (
    subscription_dates_check[
        "subscription_end_date"
    ]
    <
    subscription_dates_check[
        "subscription_start_date"
    ]
).sum()

print(
    "End dates before start dates:",
    invalid_subscription_dates
)

End dates before start dates: 0

### Save the clean version temporarily as raw

In [26]:
# -------------------------------------------------
# Save subscriptions dataset
# -------------------------------------------------

subscriptions_file = (
    RAW_DATA_DIR / "subscriptions.csv"
)

subscriptions_df.to_csv(
    subscriptions_file,
    index=False
)

print(f"Saved: {subscriptions_file}")
print(
    f"Rows: {len(subscriptions_df):,}"
)

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\subscriptions.csv
Rows: 72,000

### Generate payments.csv

### Prepare plan prices

In [27]:
# -------------------------------------------------
# Prepare plan pricing lookup
# -------------------------------------------------

plan_price_lookup = (
    plans_df
    .set_index("plan_id")[
        ["monthly_price", "annual_price"]
    ]
    .to_dict("index")
)

plan_price_lookup

{'P001': {'monthly_price': 0.0, 'annual_price': 0.0},
 'P002': {'monthly_price': 15.0, 'annual_price': 144.0},
 'P003': {'monthly_price': 30.0, 'annual_price': 288.0}}

### Generate payments

In [28]:
# -------------------------------------------------
# Generate payment transactions
# -------------------------------------------------

payment_rng = np.random.default_rng(SEED + 300)

payment_rows = []

paid_subscriptions = subscriptions_df[
    (subscriptions_df["plan_id"] != "P001")
    &
    (subscriptions_df["subscription_status"] != "Trial")
].copy()

for _, row in paid_subscriptions.iterrows():

    subscription_id = row["subscription_id"]
    plan_id = row["plan_id"]
    billing_cycle = row["billing_cycle"]

    start_date = pd.Timestamp(
        row["subscription_start_date"]
    )

    if pd.notna(row["subscription_end_date"]):
        effective_end_date = min(
            pd.Timestamp(row["subscription_end_date"]),
            CURRENT_DATE
        )
    else:
        effective_end_date = CURRENT_DATE

    # Skip impossible or zero-length periods
    if effective_end_date < start_date:
        continue

    if billing_cycle == "Monthly":

        amount = float(
            plan_price_lookup[
                plan_id
            ]["monthly_price"]
        )

        payment_dates = pd.date_range(
            start=start_date,
            end=effective_end_date,
            freq=pd.DateOffset(months=1)
        )

    else:

        amount = float(
            plan_price_lookup[
                plan_id
            ]["annual_price"]
        )

        payment_dates = pd.date_range(
            start=start_date,
            end=effective_end_date,
            freq=pd.DateOffset(years=1)
        )

    for payment_date in payment_dates:

        payment_status = payment_rng.choice(
            [
                "Successful",
                "Failed",
                "Refunded"
            ],
            p=[
                0.94,
                0.04,
                0.02
            ]
        )

        payment_method = payment_rng.choice(
            [
                "Card",
                "PayPal",
                "Bank Transfer"
            ],
            p=[
                0.72,
                0.18,
                0.10
            ]
        )

        payment_rows.append({
            "subscription_id": subscription_id,
            "payment_timestamp": (
                payment_date
                + pd.Timedelta(
                    hours=int(
                        payment_rng.integers(0, 24)
                    ),
                    minutes=int(
                        payment_rng.integers(0, 60)
                    )
                )
            ),
            "amount": amount,
            "currency": "USD",
            "payment_status": payment_status,
            "payment_method_type": payment_method
        })

payments_df = pd.DataFrame(payment_rows)

payments_df.head()

,subscription_id,payment_timestamp,amount,currency,payment_status,payment_method_type
0,SUB000001,2026-08-01 03:08:00,144.0,USD,Successful,Card
1,SUB000003,2026-05-24 07:49:00,15.0,USD,Successful,Card
2,SUB000003,2026-06-24 07:15:00,15.0,USD,Successful,Card
3,SUB000003,2026-07-24 09:53:00,15.0,USD,Successful,Card
4,SUB000003,2026-08-24 03:42:00,15.0,USD,Successful,Card

### Create payment IDs and invoice IDs

In [29]:
# -------------------------------------------------
# Create payment and invoice identifiers
# -------------------------------------------------

payments_df.insert(
    0,
    "payment_id",
    [
        f"PAY{str(i).zfill(7)}"
        for i in range(
            1,
            len(payments_df) + 1
        )
    ]
)

payments_df["invoice_id"] = [
    f"INV{str(i).zfill(7)}"
    for i in range(
        1,
        len(payments_df) + 1
    )
]

payments_df.head()

,payment_id,subscription_id,payment_timestamp,amount,currency,payment_status,payment_method_type,invoice_id
0,PAY0000001,SUB000001,2026-08-01 03:08:00,144.0,USD,Successful,Card,INV0000001
1,PAY0000002,SUB000003,2026-05-24 07:49:00,15.0,USD,Successful,Card,INV0000002
2,PAY0000003,SUB000003,2026-06-24 07:15:00,15.0,USD,Successful,Card,INV0000003
3,PAY0000004,SUB000003,2026-07-24 09:53:00,15.0,USD,Successful,Card,INV0000004
4,PAY0000005,SUB000003,2026-08-24 03:42:00,15.0,USD,Successful,Card,INV0000005

### Validate payment volume

In [30]:
# -------------------------------------------------
# Validate payment generation
# -------------------------------------------------

print(
    "Total payment transactions:",
    f"{len(payments_df):,}"
)

print()

print("Payment status distribution:")
print(
    payments_df["payment_status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print()

print("Payment method distribution:")
print(
    payments_df["payment_method_type"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print()

print(
    "Unique payment IDs:",
    payments_df["payment_id"].nunique()
)

Total payment transactions: 208,381

Payment status distribution:
payment_status
Successful    94.02
Failed         3.98
Refunded       1.99
Name: proportion, dtype: float64

Payment method distribution:
payment_method_type
Card             72.01
PayPal           18.01
Bank Transfer     9.98
Name: proportion, dtype: float64

Unique payment IDs: 208381

### Check Free subscriptions didn't generate payments

In [31]:
# -------------------------------------------------
# Verify Free plans produced no payments
# -------------------------------------------------

payment_plan_check = payments_df.merge(
    subscriptions_df[
        [
            "subscription_id",
            "plan_id"
        ]
    ],
    on="subscription_id",
    how="left"
)

free_plan_payments = (
    payment_plan_check["plan_id"]
    == "P001"
).sum()

print(
    "Payments linked to Free plans:",
    free_plan_payments
)

Payments linked to Free plans: 0

### Check payment foreign keys

In [32]:
# -------------------------------------------------
# Validate payment foreign keys
# -------------------------------------------------

invalid_payment_fk = (
    ~payments_df["subscription_id"].isin(
        subscriptions_df["subscription_id"]
    )
).sum()

print(
    "Invalid subscription references:",
    invalid_payment_fk
)

Invalid subscription references: 0

### Revenue sanity check

In [33]:
# -------------------------------------------------
# Basic payment revenue sanity check
# -------------------------------------------------

successful_revenue = (
    payments_df.loc[
        payments_df["payment_status"]
        == "Successful",
        "amount"
    ]
    .sum()
)

print(
    "Successful payment revenue:",
    f"${successful_revenue:,.2f}"
)

print()

print(
    payments_df.groupby(
        "payment_status"
    )["amount"]
    .agg(
        transactions="count",
        total_amount="sum"
    )
    .round(2)
)

Successful payment revenue: $5,949,675.00

                transactions  total_amount
payment_status
Failed                  8301      255051.0
Refunded                4150      133716.0
Successful            195930     5949675.0

### Save payments.csv

In [34]:
# -------------------------------------------------
# Save payments dataset
# -------------------------------------------------

payments_file = (
    RAW_DATA_DIR / "payments.csv"
)

payments_df.to_csv(
    payments_file,
    index=False
)

print(f"Saved: {payments_file}")
print(
    f"Rows: {len(payments_df):,}"
)

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\payments.csv
Rows: 208,381

## Add controlled issues to subscriptions and payments

### Create imperfect subscriptions_raw_df

In [35]:
# -------------------------------------------------
# Create raw subscriptions dataset with
# controlled data-quality issues
# -------------------------------------------------

subscriptions_raw_df = subscriptions_df.copy()

sub_dq_rng = np.random.default_rng(SEED + 400)

available_indexes = np.arange(len(subscriptions_raw_df))
sub_dq_rng.shuffle(available_indexes)

cursor = 0

def get_sub_indexes(n):
    global cursor
    selected = available_indexes[cursor:cursor + n]
    cursor += n
    return selected

In [36]:
# Invalid plan IDs
invalid_plan_idx = get_sub_indexes(40)

subscriptions_raw_df.loc[
    invalid_plan_idx,
    "plan_id"
] = "P999"


# Invalid billing cycles
invalid_billing_idx = get_sub_indexes(35)

subscriptions_raw_df.loc[
    invalid_billing_idx,
    "billing_cycle"
] = "Weekly"


# Invalid subscription statuses
invalid_status_idx = get_sub_indexes(30)

subscriptions_raw_df.loc[
    invalid_status_idx,
    "subscription_status"
] = "Unknown"


# End date before start date
invalid_date_idx = get_sub_indexes(25)

subscriptions_raw_df.loc[
    invalid_date_idx,
    "subscription_end_date"
] = (
    pd.to_datetime(
        subscriptions_raw_df.loc[
            invalid_date_idx,
            "subscription_start_date"
        ]
    )
    - pd.Timedelta(days=10)
).dt.date


# Both user and organization populated
both_owner_idx = get_sub_indexes(25)

subscriptions_raw_df.loc[
    both_owner_idx,
    "organization_id"
] = np.random.choice(
    organizations_df["organization_id"],
    size=len(both_owner_idx)
)


# Cancelled subscription without end date
missing_end_idx = get_sub_indexes(25)

subscriptions_raw_df.loc[
    missing_end_idx,
    "subscription_status"
] = "Cancelled"

subscriptions_raw_df.loc[
    missing_end_idx,
    "subscription_end_date"
] = None

print("Subscription data-quality issues added.")

Subscription data-quality issues added.

### Add duplicate subscription records

In [37]:
duplicate_sub_count = 50

duplicate_sub_rows = subscriptions_raw_df.sample(
    n=duplicate_sub_count,
    random_state=SEED
).copy()

subscriptions_raw_df = pd.concat(
    [
        subscriptions_raw_df,
        duplicate_sub_rows
    ],
    ignore_index=True
)

print(
    "Clean subscriptions:",
    len(subscriptions_df)
)

print(
    "Raw subscriptions:",
    len(subscriptions_raw_df)
)

Clean subscriptions: 72000
Raw subscriptions: 72050

### Save imperfect subscription raw file

In [38]:
subscriptions_raw_df.to_csv(
    RAW_DATA_DIR / "subscriptions.csv",
    index=False
)

print(
    "Saved:",
    RAW_DATA_DIR / "subscriptions.csv"
)

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\subscriptions.csv

### Now do the same for payments

In [39]:
# -------------------------------------------------
# Create raw payments dataset with
# controlled data-quality issues
# -------------------------------------------------

payments_raw_df = payments_df.copy()

payment_dq_rng = np.random.default_rng(SEED + 500)

available_payment_indexes = np.arange(
    len(payments_raw_df)
)

payment_dq_rng.shuffle(
    available_payment_indexes
)

payment_cursor = 0

def get_payment_indexes(n):
    global payment_cursor

    selected = available_payment_indexes[
        payment_cursor:
        payment_cursor + n
    ]

    payment_cursor += n

    return selected

In [40]:
# Broken subscription references
broken_fk_idx = get_payment_indexes(50)

payments_raw_df.loc[
    broken_fk_idx,
    "subscription_id"
] = "SUB999999"


# Invalid payment statuses
invalid_payment_status_idx = get_payment_indexes(40)

payments_raw_df.loc[
    invalid_payment_status_idx,
    "payment_status"
] = "PendingUnknown"


# Invalid currency values
invalid_currency_idx = get_payment_indexes(30)

payments_raw_df.loc[
    invalid_currency_idx,
    "currency"
] = "XYZ"


# Negative payment amounts
negative_amount_idx = get_payment_indexes(25)

payments_raw_df.loc[
    negative_amount_idx,
    "amount"
] = -10.00


# Missing payment methods
missing_method_idx = get_payment_indexes(50)

payments_raw_df.loc[
    missing_method_idx,
    "payment_method_type"
] = None

print("Payment data-quality issues added.")

Payment data-quality issues added.

In [41]:
duplicate_payment_count = 75

duplicate_payment_rows = payments_raw_df.sample(
    n=duplicate_payment_count,
    random_state=SEED
).copy()

payments_raw_df = pd.concat(
    [
        payments_raw_df,
        duplicate_payment_rows
    ],
    ignore_index=True
)

print(
    "Clean payments:",
    len(payments_df)
)

print(
    "Raw payments:",
    len(payments_raw_df)
)

Clean payments: 208381
Raw payments: 208456

In [42]:
payments_raw_df.to_csv(
    RAW_DATA_DIR / "payments.csv",
    index=False
)

print(
    "Saved:",
    RAW_DATA_DIR / "payments.csv"
)

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\payments.csv

### Generate sessions.csv

### Build an internal user behavior profile

In [43]:
# -------------------------------------------------
# Build synthetic user behavior profiles
# -------------------------------------------------

session_rng = np.random.default_rng(SEED + 600)

user_behavior_df = users_df[
    [
        "user_id",
        "registration_timestamp",
        "signup_platform",
        "account_status"
    ]
].copy()

# Get direct user subscription information
user_subscription_profile = (
    subscriptions_df[
        subscriptions_df["user_id"].notna()
    ][
        [
            "user_id",
            "plan_id",
            "subscription_status"
        ]
    ]
    .drop_duplicates(
        subset=["user_id"],
        keep="last"
    )
)

user_behavior_df = user_behavior_df.merge(
    user_subscription_profile,
    on="user_id",
    how="left"
)

user_behavior_df.head()

,user_id,registration_timestamp,signup_platform,account_status,plan_id,subscription_status
0,U000001,2024-09-11,Web,Active,P002,Active
1,U000002,2025-05-26,iOS,Active,P001,Cancelled
2,U000003,2026-01-09,Web,Deleted,P002,Active
3,U000004,2026-02-09,Web,Active,NaN,NaN
4,U000005,2025-09-26,iOS,Active,NaN,NaN

### Assign engagement segments

In [44]:
# -------------------------------------------------
# Assign synthetic engagement segments
# -------------------------------------------------

user_behavior_df["engagement_segment"] = None


# Active paid customers
mask = (
    user_behavior_df["plan_id"].isin(["P002", "P003"])
    &
    (user_behavior_df["subscription_status"] == "Active")
)

user_behavior_df.loc[
    mask,
    "engagement_segment"
] = session_rng.choice(
    ["High", "Medium", "Low", "Dormant"],
    size=mask.sum(),
    p=[0.35, 0.45, 0.15, 0.05]
)


# Cancelled / expired customers
mask = user_behavior_df[
    "subscription_status"
].isin(["Cancelled", "Expired"])

user_behavior_df.loc[
    mask,
    "engagement_segment"
] = session_rng.choice(
    ["High", "Medium", "Low", "Dormant"],
    size=mask.sum(),
    p=[0.08, 0.22, 0.40, 0.30]
)


# Trial customers
mask = (
    user_behavior_df["subscription_status"]
    == "Trial"
)

user_behavior_df.loc[
    mask,
    "engagement_segment"
] = session_rng.choice(
    ["High", "Medium", "Low", "Dormant"],
    size=mask.sum(),
    p=[0.20, 0.40, 0.30, 0.10]
)


# Free-plan customers
mask = (
    (user_behavior_df["plan_id"] == "P001")
    &
    user_behavior_df[
        "engagement_segment"
    ].isna()
)

user_behavior_df.loc[
    mask,
    "engagement_segment"
] = session_rng.choice(
    ["High", "Medium", "Low", "Dormant"],
    size=mask.sum(),
    p=[0.12, 0.38, 0.35, 0.15]
)


# Users without any subscription
mask = user_behavior_df[
    "engagement_segment"
].isna()

user_behavior_df.loc[
    mask,
    "engagement_segment"
] = session_rng.choice(
    ["High", "Medium", "Low", "Dormant"],
    size=mask.sum(),
    p=[0.08, 0.30, 0.40, 0.22]
)

### Check the segments

In [45]:
print("Engagement segment distribution:")

print(
    user_behavior_df[
        "engagement_segment"
    ]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Engagement segment distribution:
engagement_segment
Medium     34.23
Low        32.72
Dormant    17.82
High       15.23
Name: proportion, dtype: float64

### Determine how many sessions each user gets

In [46]:
# -------------------------------------------------
# Generate number of sessions per user
# -------------------------------------------------

session_lambda_map = {
    "High": 20.0,
    "Medium": 10.0,
    "Low": 4.0,
    "Dormant": 0.6
}

user_behavior_df[
    "base_session_lambda"
] = user_behavior_df[
    "engagement_segment"
].map(session_lambda_map)


# Older accounts have had more time to generate sessions
registration_dates = pd.to_datetime(
    user_behavior_df[
        "registration_timestamp"
    ]
)

account_age_days = (
    CURRENT_DATE
    - registration_dates.dt.normalize()
).dt.days.clip(lower=0)

max_account_age = max(
    account_age_days.max(),
    1
)

age_factor = (
    0.40
    +
    0.60
    * (
        account_age_days
        / max_account_age
    )
)


# Reduce expected activity for suspended/deleted users
status_multiplier = (
    user_behavior_df[
        "account_status"
    ]
    .map({
        "Active": 1.00,
        "Suspended": 0.40,
        "Deleted": 0.15
    })
    .fillna(1.00)
)


effective_lambda = (
    user_behavior_df[
        "base_session_lambda"
    ]
    * age_factor
    * status_multiplier
)


user_behavior_df[
    "session_count"
] = session_rng.poisson(
    effective_lambda
)

print(
    "Expected total sessions:",
    f"{user_behavior_df['session_count'].sum():,}"
)

Expected total sessions: 535,936

### Check session counts by engagement type

In [47]:
print(
    user_behavior_df.groupby(
        "engagement_segment"
    )["session_count"]
    .agg(
        users="count",
        avg_sessions="mean",
        median_sessions="median",
        total_sessions="sum"
    )
    .round(2)
)

                    users  avg_sessions  median_sessions  total_sessions
engagement_segment
Dormant             17823          0.41              0.0            7256
High                15230         13.66             13.0          208075
Low                 32721          2.70              2.0           88382
Medium              34226          6.78              7.0          232223

### Generate the actual session rows

In [48]:
# -------------------------------------------------
# Expand users into individual session records
# -------------------------------------------------

session_counts = (
    user_behavior_df[
        "session_count"
    ]
    .to_numpy()
)

user_row_indexes = np.repeat(
    np.arange(
        len(user_behavior_df)
    ),
    session_counts
)

N_SESSIONS = len(user_row_indexes)

print(
    "Generating sessions:",
    f"{N_SESSIONS:,}"
)

Generating sessions: 535,936

In [49]:
session_user_ids = (
    user_behavior_df[
        "user_id"
    ]
    .to_numpy()[
        user_row_indexes
    ]
)

session_signup_platforms = (
    user_behavior_df[
        "signup_platform"
    ]
    .to_numpy()[
        user_row_indexes
    ]
)

session_registration_dates = (
    pd.to_datetime(
        user_behavior_df[
            "registration_timestamp"
        ]
    )
    .dt.normalize()
    .to_numpy()[
        user_row_indexes
    ]
)

### Generate realistic session dates

In [50]:
# -------------------------------------------------
# Generate session timestamps
# -------------------------------------------------

DATA_END_TIMESTAMP = pd.Timestamp(
    "2026-08-31 23:59:59"
)

registration_series = pd.Series(
    pd.to_datetime(
        session_registration_dates
    )
)

days_available = (
    DATA_END_TIMESTAMP.normalize()
    - registration_series
).dt.days.clip(lower=0).to_numpy()

random_day_offsets = (
    session_rng.random(N_SESSIONS)
    * (days_available + 1)
).astype(int)

random_seconds = session_rng.integers(
    0,
    24 * 60 * 60,
    size=N_SESSIONS
)

session_start_timestamp = (
    pd.to_datetime(
        session_registration_dates
    )
    +
    pd.to_timedelta(
        random_day_offsets,
        unit="D"
    )
    +
    pd.to_timedelta(
        random_seconds,
        unit="s"
    )
)

### Assign session platform

In [51]:
# -------------------------------------------------
# Assign session platform
# -------------------------------------------------

keep_signup_platform = (
    session_rng.random(
        N_SESSIONS
    ) < 0.78
)

alternate_platform = (
    session_rng.choice(
        ["Web", "iOS", "Android"],
        size=N_SESSIONS,
        p=[0.60, 0.19, 0.21]
    )
)

session_platform = np.where(
    keep_signup_platform,
    session_signup_platforms,
    alternate_platform
)

### Generate device type

In [52]:
# -------------------------------------------------
# Generate device types
# -------------------------------------------------

device_type = np.empty(
    N_SESSIONS,
    dtype=object
)

web_mask = (
    session_platform == "Web"
)

mobile_mask = (
    ~web_mask
)


device_type[web_mask] = (
    session_rng.choice(
        [
            "Desktop",
            "Mobile",
            "Tablet"
        ],
        size=web_mask.sum(),
        p=[0.82, 0.10, 0.08]
    )
)

device_type[mobile_mask] = (
    session_rng.choice(
        [
            "Mobile",
            "Tablet"
        ],
        size=mobile_mask.sum(),
        p=[0.94, 0.06]
    )
)

### Session status and duration

In [53]:
# -------------------------------------------------
# Generate session status and duration
# -------------------------------------------------

session_status = session_rng.choice(
    [
        "Completed",
        "Abandoned"
    ],
    size=N_SESSIONS,
    p=[
        0.95,
        0.05
    ]
)

session_duration_minutes = (
    session_rng.lognormal(
        mean=3.0,
        sigma=0.65,
        size=N_SESSIONS
    )
)

session_duration_minutes = np.clip(
    session_duration_minutes,
    2,
    180
)


# Abandoned sessions tend to be shorter
abandoned_mask = (
    session_status == "Abandoned"
)

session_duration_minutes[
    abandoned_mask
] = np.clip(
    session_duration_minutes[
        abandoned_mask
    ] * 0.30,
    1,
    30
)


session_end_timestamp = (
    session_start_timestamp
    +
    pd.to_timedelta(
        session_duration_minutes,
        unit="m"
    )
)

### Build sessions_df

In [54]:
# -------------------------------------------------
# Build sessions table
# -------------------------------------------------

sessions_df = pd.DataFrame({
    "session_id": [
        f"S{str(i).zfill(7)}"
        for i in range(
            1,
            N_SESSIONS + 1
        )
    ],
    "user_id": session_user_ids,
    "session_start_timestamp":
        session_start_timestamp,
    "session_end_timestamp":
        session_end_timestamp,
    "platform": session_platform,
    "device_type": device_type,
    "session_status": session_status
})

sessions_df.head()

,session_id,user_id,session_start_timestamp,session_end_timestamp,platform,device_type,session_status
0,S0000001,U000001,2025-12-27 22:40:41,2025-12-27 23:14:30.152001542,Web,Desktop,Completed
1,S0000002,U000001,2024-10-05 03:51:44,2024-10-05 04:01:18.767429084,Android,Mobile,Completed
2,S0000003,U000001,2025-08-24 18:25:53,2025-08-24 18:35:30.251052722,Web,Desktop,Completed
3,S0000004,U000001,2025-06-01 16:08:47,2025-06-01 16:17:13.866390296,Web,Desktop,Completed
4,S0000005,U000001,2025-09-10 10:17:56,2025-09-10 10:28:44.251281554,Android,Mobile,Completed

### Validate

In [55]:
print(
    "Total sessions:",
    f"{len(sessions_df):,}"
)

print(
    "Unique session IDs:",
    f"{sessions_df['session_id'].nunique():,}"
)

print(
    "Users with at least one session:",
    f"{sessions_df['user_id'].nunique():,}"
)

print(
    "Invalid user references:",
    (
        ~sessions_df["user_id"]
        .isin(users_df["user_id"])
    ).sum()
)

print(
    "Sessions ending before they start:",
    (
        sessions_df[
            "session_end_timestamp"
        ]
        <
        sessions_df[
            "session_start_timestamp"
        ]
    ).sum()
)

Total sessions: 535,936
Unique session IDs: 535,936
Users with at least one session: 84,534
Invalid user references: 0
Sessions ending before they start: 0

### Save sessions.csv

In [56]:
# -------------------------------------------------
# Save sessions dataset
# -------------------------------------------------

sessions_file = (
    RAW_DATA_DIR / "sessions.csv"
)

sessions_df.to_csv(
    sessions_file,
    index=False
)

print(
    f"Saved: {sessions_file}"
)

print(
    f"Rows: {len(sessions_df):,}"
)

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\sessions.csv
Rows: 535,936

### Fix the session cutoff

In [57]:
# -------------------------------------------------
# Ensure sessions do not extend past data cutoff
# -------------------------------------------------

sessions_df["session_end_timestamp"] = (
    pd.to_datetime(
        sessions_df["session_end_timestamp"]
    )
    .clip(upper=DATA_END_TIMESTAMP)
)

print(
    "Sessions after data cutoff:",
    (
        sessions_df["session_end_timestamp"]
        > DATA_END_TIMESTAMP
    ).sum()
)

Sessions after data cutoff: 0

In [58]:
sessions_df.to_csv(
    RAW_DATA_DIR / "sessions.csv",
    index=False
)

print("Corrected sessions.csv saved.")

Corrected sessions.csv saved.

## Generate product_events.csv

### Determine each user's effective plan

In [59]:
# -------------------------------------------------
# Determine effective user plan
# -------------------------------------------------

direct_user_plans = (
    subscriptions_df[
        subscriptions_df["user_id"].notna()
    ]
    .drop_duplicates(
        subset="user_id",
        keep="last"
    )[
        ["user_id", "plan_id"]
    ]
    .rename(
        columns={
            "plan_id": "direct_plan_id"
        }
    )
)

organization_plans = (
    subscriptions_df[
        subscriptions_df["organization_id"].notna()
    ]
    .drop_duplicates(
        subset="organization_id",
        keep="last"
    )[
        ["organization_id", "plan_id"]
    ]
    .rename(
        columns={
            "plan_id": "organization_plan_id"
        }
    )
)

user_plan_df = (
    users_df[
        ["user_id", "organization_id"]
    ]
    .merge(
        direct_user_plans,
        on="user_id",
        how="left"
    )
    .merge(
        organization_plans,
        on="organization_id",
        how="left"
    )
)

user_plan_df["effective_plan_id"] = (
    user_plan_df["direct_plan_id"]
    .fillna(
        user_plan_df["organization_plan_id"]
    )
    .fillna("P001")
)

user_plan_df[
    ["user_id", "effective_plan_id"]
].head()

   user_id effective_plan_id
0  U000001              P002
1  U000002              P001
2  U000003              P002
3  U000004              P001
4  U000005              P003

### Attach plans to sessions

In [60]:
sessions_events_base = sessions_df.merge(
    user_plan_df[
        [
            "user_id",
            "effective_plan_id"
        ]
    ],
    on="user_id",
    how="left"
)

sessions_events_base[
    "effective_plan_id"
] = sessions_events_base[
    "effective_plan_id"
].fillna("P001")

sessions_events_base.head()

,session_id,user_id,session_start_timestamp,session_end_timestamp,platform,device_type,session_status,effective_plan_id
0,S0000001,U000001,2025-12-27 22:40:41,2025-12-27 23:14:30.152001542,Web,Desktop,Completed,P002
1,S0000002,U000001,2024-10-05 03:51:44,2024-10-05 04:01:18.767429084,Android,Mobile,Completed,P002
2,S0000003,U000001,2025-08-24 18:25:53,2025-08-24 18:35:30.251052722,Web,Desktop,Completed,P002
3,S0000004,U000001,2025-06-01 16:08:47,2025-06-01 16:17:13.866390296,Web,Desktop,Completed,P002
4,S0000005,U000001,2025-09-10 10:17:56,2025-09-10 10:28:44.251281554,Android,Mobile,Completed,P002

### Calculate events per session

In [61]:
# -------------------------------------------------
# Determine number of product events per session
# -------------------------------------------------

event_rng = np.random.default_rng(SEED + 700)

session_duration_minutes = (
    (
        sessions_events_base[
            "session_end_timestamp"
        ]
        -
        sessions_events_base[
            "session_start_timestamp"
        ]
    )
    .dt.total_seconds()
    .div(60)
    .clip(lower=0)
)

event_lambda = (
    2.6
    +
    np.minimum(
        session_duration_minutes / 60,
        1.5
    )
)

# Abandoned sessions have fewer actions
abandoned_mask = (
    sessions_events_base[
        "session_status"
    ]
    == "Abandoned"
)

event_lambda.loc[
    abandoned_mask
] = 1.4

sessions_events_base[
    "event_count"
] = np.maximum(
    1,
    event_rng.poisson(
        event_lambda.to_numpy()
    )
)

TOTAL_EVENTS = int(
    sessions_events_base[
        "event_count"
    ].sum()
)

print(
    "Estimated product events:",
    f"{TOTAL_EVENTS:,}"
)

Estimated product events: 1,601,461

### Define feature → event mapping

In [62]:
feature_event_map = {
    "F001": "project_created",
    "F002": "task_updated",
    "F003": "file_uploaded",
    "F004": "collaboration_action",
    "F005": "calendar_synced",
    "F006": "automation_run",
    "F007": "dashboard_viewed",
    "F008": "analytics_report_viewed",
    "F009": "permission_changed",
    "F010": "audit_log_viewed",
    "F011": "api_request",
    "F012": "ai_assistant_used"
}

feature_weights = {
    "F001": 0.16,
    "F002": 0.20,
    "F003": 0.15,
    "F004": 0.10,
    "F005": 0.08,
    "F006": 0.08,
    "F007": 0.07,
    "F008": 0.04,
    "F009": 0.03,
    "F010": 0.03,
    "F011": 0.03,
    "F012": 0.03
}

### Prepare feature eligibility

In [63]:
plan_rank = {
    "P001": 1,
    "P002": 2,
    "P003": 3
}

minimum_plan_rank = {
    "Free": 1,
    "Pro": 2,
    "Business": 3
}

feature_meta = features_df.copy()

feature_meta[
    "minimum_plan_rank"
] = feature_meta[
    "minimum_plan"
].map(minimum_plan_rank)

feature_meta[
    "launch_timestamp"
] = pd.to_datetime(
    feature_meta["launch_date"]
)

feature_meta[
    [
        "feature_id",
        "minimum_plan",
        "launch_timestamp"
    ]
]

   feature_id minimum_plan launch_timestamp
0        F001         Free       2024-01-15
1        F002         Free       2024-01-15
2        F003         Free       2024-03-01
3        F004          Pro       2024-04-10
4        F005          Pro       2024-05-20
5        F006          Pro       2024-07-01
6        F007          Pro       2024-08-15
7        F008     Business       2024-10-01
8        F009     Business       2024-11-15
9        F010     Business       2025-01-10
10       F011     Business       2025-03-01
11       F012          Pro       2026-03-15

### Generate the large CSV in chunks

In [64]:
# -------------------------------------------------
# Generate product events in chunks
# -------------------------------------------------

PRODUCT_EVENTS_FILE = (
    RAW_DATA_DIR / "product_events.csv"
)

CHUNK_SIZE = 50_000

event_counter = 0
first_chunk = True

generic_event_names = [
    "login",
    "navigation_view",
    "search_used"
]

for chunk_start in range(
    0,
    len(sessions_events_base),
    CHUNK_SIZE
):

    chunk = sessions_events_base.iloc[
        chunk_start:
        chunk_start + CHUNK_SIZE
    ].reset_index(drop=True)

    counts = (
        chunk["event_count"]
        .to_numpy()
    )

    repeated_indexes = np.repeat(
        np.arange(len(chunk)),
        counts
    )

    n_events = len(repeated_indexes)

    session_ids = (
        chunk["session_id"]
        .to_numpy()[repeated_indexes]
    )

    user_ids = (
        chunk["user_id"]
        .to_numpy()[repeated_indexes]
    )

    platforms = (
        chunk["platform"]
        .to_numpy()[repeated_indexes]
    )

    plans = (
        chunk["effective_plan_id"]
        .to_numpy()[repeated_indexes]
    )

    starts = pd.to_datetime(
        chunk[
            "session_start_timestamp"
        ]
        .to_numpy()[repeated_indexes]
    )

    ends = pd.to_datetime(
        chunk[
            "session_end_timestamp"
        ]
        .to_numpy()[repeated_indexes]
    )

    duration_seconds = (
        (ends - starts)
        .total_seconds()
    )

    offsets = (
        event_rng.random(n_events)
        * duration_seconds
    )

    event_timestamps = (
        starts
        +
        pd.to_timedelta(
            offsets,
            unit="s"
        )
    )

    # ---------------------------------------------
    # Generic vs feature-specific events
    # ---------------------------------------------

    generic_mask = (
        event_rng.random(n_events)
        < 0.20
    )

    feature_ids = np.full(
        n_events,
        None,
        dtype=object
    )

    event_names = np.empty(
        n_events,
        dtype=object
    )

    event_names[
        generic_mask
    ] = event_rng.choice(
        generic_event_names,
        size=generic_mask.sum(),
        p=[0.45, 0.35, 0.20]
    )

    # ---------------------------------------------
    # Generate feature events by plan + launch date
    # ---------------------------------------------

    feature_event_indexes = np.where(
        ~generic_mask
    )[0]

    for plan_id in [
        "P001",
        "P002",
        "P003"
    ]:

        plan_indexes = feature_event_indexes[
            plans[
                feature_event_indexes
            ]
            == plan_id
        ]

        if len(plan_indexes) == 0:
            continue

        rank = plan_rank[plan_id]

        eligible_features = feature_meta[
            feature_meta[
                "minimum_plan_rank"
            ] <= rank
        ]

        for event_index in plan_indexes:

            timestamp = (
                event_timestamps[
                    event_index
                ]
            )

            available_features = (
                eligible_features[
                    eligible_features[
                        "launch_timestamp"
                    ]
                    <= timestamp
                ]
            )

            # Very early sessions may occur before
            # any feature was officially launched
            if available_features.empty:

                feature_ids[
                    event_index
                ] = None

                event_names[
                    event_index
                ] = event_rng.choice(
                    generic_event_names
                )

                continue

            candidate_ids = (
                available_features[
                    "feature_id"
                ]
                .tolist()
            )

            candidate_weights = np.array(
                [
                    feature_weights[
                        feature_id
                    ]
                    for feature_id
                    in candidate_ids
                ]
            )

            candidate_weights = (
                candidate_weights
                /
                candidate_weights.sum()
            )

            selected_feature = (
                event_rng.choice(
                    candidate_ids,
                    p=candidate_weights
                )
            )

            feature_ids[
                event_index
            ] = selected_feature

            event_names[
                event_index
            ] = feature_event_map[
                selected_feature
            ]

    # ---------------------------------------------
    # Build chunk DataFrame
    # ---------------------------------------------

    event_ids = [
        f"E{str(i).zfill(8)}"
        for i in range(
            event_counter + 1,
            event_counter
            + n_events
            + 1
        )
    ]

    events_chunk_df = pd.DataFrame({
        "event_id": event_ids,
        "user_id": user_ids,
        "session_id": session_ids,
        "feature_id": feature_ids,
        "event_name": event_names,
        "event_timestamp": event_timestamps,
        "platform": platforms,
        "event_value": None
    })

    events_chunk_df.to_csv(
        PRODUCT_EVENTS_FILE,
        mode=(
            "w"
            if first_chunk
            else "a"
        ),
        header=first_chunk,
        index=False
    )

    event_counter += n_events
    first_chunk = False

    print(
        f"Generated {event_counter:,} events..."
    )

print()
print(
    "Final product event rows:",
    f"{event_counter:,}"
)

Generated 149,404 events...
Generated 299,414 events...
Generated 447,950 events...
Generated 598,064 events...
Generated 747,754 events...
Generated 897,486 events...
Generated 1,046,585 events...
Generated 1,196,135 events...
Generated 1,345,221 events...
Generated 1,494,508 events...
Generated 1,601,461 events...

Final product event rows: 1,601,461

### Read a small sample

In [65]:
product_events_sample = pd.read_csv(
    PRODUCT_EVENTS_FILE,
    nrows=10
)

product_events_sample

,event_id,user_id,session_id,feature_id,event_name,event_timestamp,platform,event_value
0,E00000001,U000001,S0000001,F001,project_created,2025-12-27 22:55:24.916526811,Web,NaN
1,E00000002,U000001,S0000001,F005,calendar_synced,2025-12-27 22:47:03.826409808,Web,NaN
2,E00000003,U000001,S0000001,NaN,navigation_view,2025-12-27 22:40:43.191452549,Web,NaN
3,E00000004,U000001,S0000001,F002,task_updated,2025-12-27 22:43:51.954050409,Web,NaN
4,E00000005,U000001,S0000001,F003,file_uploaded,2025-12-27 22:45:19.331079840,Web,NaN
5,E00000006,U000001,S0000002,NaN,navigation_view,2024-10-05 03:57:54.550963439,Android,NaN
6,E00000007,U000001,S0000002,NaN,login,2024-10-05 03:58:25.754152915,Android,NaN
7,E00000008,U000001,S0000003,NaN,navigation_view,2025-08-24 18:31:43.796451509,Web,NaN
8,E00000009,U000001,S0000003,F004,collaboration_action,2025-08-24 18:26:31.820514861,Web,NaN
9,E00000010,U000001,S0000004,F003,file_uploaded,2025-06-01 16:09:57.339056863,Web,NaN

### Confirm CSV row count

In [66]:
# -------------------------------------------------
# Count product event rows without loading file
# -------------------------------------------------

with open(
    PRODUCT_EVENTS_FILE,
    "r",
    encoding="utf-8"
) as file:

    product_event_row_count = (
        sum(1 for _ in file) - 1
    )

print(
    "product_events.csv rows:",
    f"{product_event_row_count:,}"
)

product_events.csv rows: 1,601,461

## Generate onboarding_events.csv

### Define onboarding steps

In [67]:
# -------------------------------------------------
# Define NovaFlow onboarding steps
# -------------------------------------------------

onboarding_steps = [
    (1, "Account Created"),
    (2, "Email Verified"),
    (3, "Profile Completed"),
    (4, "Workspace Preferences"),
    (5, "Tutorial Completed"),
    (6, "First Project Created")
]

onboarding_steps

[(1, 'Account Created'),
 (2, 'Email Verified'),
 (3, 'Profile Completed'),
 (4, 'Workspace Preferences'),
 (5, 'Tutorial Completed'),
 (6, 'First Project Created')]

### Assign onboarding completion depth

In [68]:
# -------------------------------------------------
# Assign onboarding completion depth
# -------------------------------------------------

onboarding_rng = np.random.default_rng(SEED + 800)

onboarding_users = users_df[
    [
        "user_id",
        "registration_timestamp",
        "signup_platform"
    ]
].copy()

completion_depths = onboarding_rng.choice(
    [1, 2, 3, 4, 5, 6],
    size=len(onboarding_users),
    p=[
        0.04,
        0.06,
        0.09,
        0.12,
        0.18,
        0.51
    ]
)

onboarding_users[
    "completion_depth"
] = completion_depths

onboarding_users[
    "completion_depth"
].value_counts(
    normalize=True
).sort_index().mul(100).round(2)

completion_depth
1     4.09
2     5.97
3     9.02
4    11.90
5    18.04
6    50.98
Name: proportion, dtype: float64

### Generate onboarding-event rows

In [69]:
# -------------------------------------------------
# Generate onboarding events
# -------------------------------------------------

onboarding_rows = []

for _, user in onboarding_users.iterrows():

    user_id = user["user_id"]

    registration_timestamp = pd.Timestamp(
        user["registration_timestamp"]
    )

    completion_depth = int(
        user["completion_depth"]
    )

    current_timestamp = (
        registration_timestamp
        +
        pd.Timedelta(
            minutes=int(
                onboarding_rng.integers(
                    1,
                    20
                )
            )
        )
    )

    for step_order, step_name in onboarding_steps:

        if step_order > completion_depth:
            break

        time_spent_seconds = int(
            onboarding_rng.integers(
                30,
                900
            )
        )

        # Last reached step may be abandoned
        if (
            step_order == completion_depth
            and completion_depth < 6
        ):
            completion_status = onboarding_rng.choice(
                [
                    "Completed",
                    "Abandoned"
                ],
                p=[
                    0.20,
                    0.80
                ]
            )
        else:
            completion_status = "Completed"

        onboarding_rows.append({
            "user_id": user_id,
            "onboarding_step": step_name,
            "step_order": step_order,
            "event_timestamp": current_timestamp,
            "completion_status": completion_status,
            "time_spent_seconds": time_spent_seconds
        })

        current_timestamp += pd.Timedelta(
            seconds=time_spent_seconds
        )

        current_timestamp += pd.Timedelta(
            minutes=int(
                onboarding_rng.integers(
                    1,
                    240
                )
            )
        )

onboarding_events_df = pd.DataFrame(
    onboarding_rows
)

print(
    "Generated onboarding events:",
    f"{len(onboarding_events_df):,}"
)

onboarding_events_df.head()

Generated onboarding events: 486,792

,user_id,onboarding_step,step_order,event_timestamp,completion_status,time_spent_seconds
0,U000001,Account Created,1,2024-09-11 00:08:00,Completed,85
1,U000001,Email Verified,2,2024-09-11 00:57:25,Completed,662
2,U000001,Profile Completed,3,2024-09-11 02:41:27,Completed,125
3,U000001,Workspace Preferences,4,2024-09-11 06:15:32,Completed,734
4,U000001,Tutorial Completed,5,2024-09-11 06:37:46,Completed,725

### Create onboarding-event IDs

In [70]:
# -------------------------------------------------
# Create onboarding event primary keys
# -------------------------------------------------

onboarding_events_df.insert(
    0,
    "onboarding_event_id",
    [
        f"ONB{str(i).zfill(7)}"
        for i in range(
            1,
            len(onboarding_events_df) + 1
        )
    ]
)

onboarding_events_df.head()

,onboarding_event_id,user_id,onboarding_step,step_order,event_timestamp,completion_status,time_spent_seconds
0,ONB0000001,U000001,Account Created,1,2024-09-11 00:08:00,Completed,85
1,ONB0000002,U000001,Email Verified,2,2024-09-11 00:57:25,Completed,662
2,ONB0000003,U000001,Profile Completed,3,2024-09-11 02:41:27,Completed,125
3,ONB0000004,U000001,Workspace Preferences,4,2024-09-11 06:15:32,Completed,734
4,ONB0000005,U000001,Tutorial Completed,5,2024-09-11 06:37:46,Completed,725

### Validate the funnel

In [71]:
# -------------------------------------------------
# Review onboarding funnel
# -------------------------------------------------

onboarding_funnel = (
    onboarding_events_df[
        onboarding_events_df[
            "completion_status"
        ] == "Completed"
    ]
    .groupby(
        [
            "step_order",
            "onboarding_step"
        ]
    )["user_id"]
    .nunique()
    .reset_index(
        name="completed_users"
    )
    .sort_values(
        "step_order"
    )
)

onboarding_funnel[
    "conversion_from_start_pct"
] = (
    onboarding_funnel[
        "completed_users"
    ]
    /
    len(users_df)
    * 100
).round(2)

onboarding_funnel

,step_order,onboarding_step,completed_users,conversion_from_start_pct
0,1,Account Created,96744,96.74
1,2,Email Verified,91093,91.09
2,3,Profile Completed,82682,82.68
3,4,Workspace Preferences,71309,71.31
4,5,Tutorial Completed,54473,54.47
5,6,First Project Created,50983,50.98

### Validate FK and time rules

In [72]:
# -------------------------------------------------
# Validate onboarding data
# -------------------------------------------------

invalid_onboarding_users = (
    ~onboarding_events_df[
        "user_id"
    ].isin(
        users_df["user_id"]
    )
).sum()

negative_time = (
    onboarding_events_df[
        "time_spent_seconds"
    ] < 0
).sum()

invalid_step_order = (
    onboarding_events_df[
        "step_order"
    ] <= 0
).sum()

print(
    "Invalid user references:",
    invalid_onboarding_users
)

print(
    "Negative time values:",
    negative_time
)

print(
    "Invalid step order:",
    invalid_step_order
)

Invalid user references: 0
Negative time values: 0
Invalid step order: 0

### Save onboarding_events.csv

In [73]:
# -------------------------------------------------
# Save onboarding events
# -------------------------------------------------

onboarding_events_file = (
    RAW_DATA_DIR
    / "onboarding_events.csv"
)

onboarding_events_df.to_csv(
    onboarding_events_file,
    index=False
)

print(
    f"Saved: {onboarding_events_file}"
)

print(
    f"Rows: {len(onboarding_events_df):,}"
)

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\onboarding_events.csv
Rows: 486,792

## Generate marketing_attribution.csv

### Define channel details

In [74]:
# -------------------------------------------------
# Define marketing attribution mappings
# -------------------------------------------------

marketing_rng = np.random.default_rng(SEED + 900)

channel_details = {
    "Organic Search": {
        "sources": ["Google", "Bing"],
        "medium": "organic"
    },
    "Paid Search": {
        "sources": ["Google Ads", "Bing Ads"],
        "medium": "cpc"
    },
    "Social": {
        "sources": ["LinkedIn", "Instagram", "Facebook", "X"],
        "medium": "social"
    },
    "Referral": {
        "sources": ["Customer Referral", "Community Referral"],
        "medium": "referral"
    },
    "Partner": {
        "sources": ["Technology Partner", "Consulting Partner"],
        "medium": "partner"
    },
    "Direct": {
        "sources": ["Direct"],
        "medium": "direct"
    },
    "Email": {
        "sources": ["Newsletter", "Lifecycle Email"],
        "medium": "email"
    }
}

landing_pages = [
    "/",
    "/pricing",
    "/features",
    "/templates",
    "/productivity",
    "/team-collaboration"
]

### Generate one primary attribution record per user

In [75]:
# -------------------------------------------------
# Generate marketing attribution records
# -------------------------------------------------

marketing_rows = []

campaign_options = {
    "Organic Search": [None],
    "Paid Search": [
        "Brand_Search",
        "SaaS_Productivity",
        "Competitor_Search",
        "Remote_Work"
    ],
    "Social": [
        "LinkedIn_Productivity",
        "Social_Awareness",
        "Creator_Campaign"
    ],
    "Referral": [
        "Customer_Referral_Program"
    ],
    "Partner": [
        "Partner_Growth_Program"
    ],
    "Direct": [None],
    "Email": [
        "Newsletter_Growth",
        "Welcome_Campaign",
        "Product_Launch"
    ]
}

for _, user in users_df.iterrows():

    user_id = user["user_id"]
    channel = user["acquisition_channel"]

    detail = channel_details[channel]

    source = marketing_rng.choice(
        detail["sources"]
    )

    medium = detail["medium"]

    campaign = marketing_rng.choice(
        campaign_options[channel]
    )

    attributed_timestamp = (
        pd.Timestamp(
            user["registration_timestamp"]
        )
        -
        pd.Timedelta(
            minutes=int(
                marketing_rng.integers(
                    0,
                    24 * 60
                )
            )
        )
    )

    marketing_rows.append({
        "user_id": user_id,
        "acquisition_channel": channel,
        "source": source,
        "medium": medium,
        "campaign_name": campaign,
        "attributed_timestamp": attributed_timestamp,
        "landing_page": marketing_rng.choice(
            landing_pages,
            p=[0.25, 0.22, 0.18, 0.12, 0.13, 0.10]
        )
    })

marketing_attribution_df = pd.DataFrame(
    marketing_rows
)

marketing_attribution_df.head()

,user_id,acquisition_channel,source,medium,campaign_name,attributed_timestamp,landing_page
0,U000001,Paid Search,Bing Ads,cpc,SaaS_Productivity,2024-09-10 05:14:00,/features
1,U000002,Direct,Direct,direct,NaN,2025-05-25 11:05:00,/
2,U000003,Referral,Community Referral,referral,Customer_Referral_Program,2026-01-08 05:39:00,/productivity
3,U000004,Paid Search,Bing Ads,cpc,Brand_Search,2026-02-08 20:27:00,/features
4,U000005,Partner,Consulting Partner,partner,Partner_Growth_Program,2025-09-25 01:10:00,/pricing

### Add IDs

In [76]:
# -------------------------------------------------
# Create attribution and campaign IDs
# -------------------------------------------------

marketing_attribution_df.insert(
    0,
    "attribution_id",
    [
        f"ATTR{str(i).zfill(6)}"
        for i in range(
            1,
            len(marketing_attribution_df) + 1
        )
    ]
)

campaign_id_map = {
    campaign: f"CMP{str(i).zfill(3)}"
    for i, campaign in enumerate(
        sorted(
            marketing_attribution_df[
                "campaign_name"
            ]
            .dropna()
            .unique()
        ),
        start=1
    )
}

marketing_attribution_df[
    "campaign_id"
] = marketing_attribution_df[
    "campaign_name"
].map(campaign_id_map)

marketing_attribution_df.head()

,attribution_id,user_id,acquisition_channel,source,medium,campaign_name,attributed_timestamp,landing_page,campaign_id
0,ATTR000001,U000001,Paid Search,Bing Ads,cpc,SaaS_Productivity,2024-09-10 05:14:00,/features,CMP010
1,ATTR000002,U000002,Direct,Direct,direct,NaN,2025-05-25 11:05:00,/,NaN
2,ATTR000003,U000003,Referral,Community Referral,referral,Customer_Referral_Program,2026-01-08 05:39:00,/productivity,CMP004
3,ATTR000004,U000004,Paid Search,Bing Ads,cpc,Brand_Search,2026-02-08 20:27:00,/features,CMP001
4,ATTR000005,U000005,Partner,Consulting Partner,partner,Partner_Growth_Program,2025-09-25 01:10:00,/pricing,CMP007

### Put columns in our designed order

In [77]:
marketing_attribution_df = (
    marketing_attribution_df[
        [
            "attribution_id",
            "user_id",
            "acquisition_channel",
            "source",
            "medium",
            "campaign_name",
            "campaign_id",
            "attributed_timestamp",
            "landing_page"
        ]
    ]
)

marketing_attribution_df.head()

,attribution_id,user_id,acquisition_channel,source,medium,campaign_name,campaign_id,attributed_timestamp,landing_page
0,ATTR000001,U000001,Paid Search,Bing Ads,cpc,SaaS_Productivity,CMP010,2024-09-10 05:14:00,/features
1,ATTR000002,U000002,Direct,Direct,direct,NaN,NaN,2025-05-25 11:05:00,/
2,ATTR000003,U000003,Referral,Community Referral,referral,Customer_Referral_Program,CMP004,2026-01-08 05:39:00,/productivity
3,ATTR000004,U000004,Paid Search,Bing Ads,cpc,Brand_Search,CMP001,2026-02-08 20:27:00,/features
4,ATTR000005,U000005,Partner,Consulting Partner,partner,Partner_Growth_Program,CMP007,2025-09-25 01:10:00,/pricing

### Validate

In [78]:
print(
    "Marketing attribution rows:",
    f"{len(marketing_attribution_df):,}"
)

print(
    "Unique attribution IDs:",
    marketing_attribution_df[
        "attribution_id"
    ].nunique()
)

print(
    "Unique users:",
    marketing_attribution_df[
        "user_id"
    ].nunique()
)

print(
    "Invalid user references:",
    (
        ~marketing_attribution_df[
            "user_id"
        ].isin(
            users_df["user_id"]
        )
    ).sum()
)

Marketing attribution rows: 100,000
Unique attribution IDs: 100000
Unique users: 100000
Invalid user references: 0

### View acquisition distribution

In [79]:
print(
    marketing_attribution_df[
        "acquisition_channel"
    ]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

acquisition_channel
Organic Search    26.04
Paid Search       19.91
Social            15.07
Direct            11.98
Referral          11.96
Partner            7.96
Email              7.08
Name: proportion, dtype: float64

### Inspect channel → source mapping

In [80]:
(
    marketing_attribution_df
    .groupby(
        [
            "acquisition_channel",
            "source"
        ]
    )
    .size()
    .reset_index(
        name="users"
    )
    .sort_values(
        [
            "acquisition_channel",
            "users"
        ],
        ascending=[
            True,
            False
        ]
    )
)

   acquisition_channel              source  users
0               Direct              Direct  11982
2                Email          Newsletter   3568
1                Email     Lifecycle Email   3515
3       Organic Search                Bing  13056
4       Organic Search              Google  12987
5          Paid Search            Bing Ads   9973
6          Paid Search          Google Ads   9938
7              Partner  Consulting Partner   3999
8              Partner  Technology Partner   3960
9             Referral  Community Referral   5984
10            Referral   Customer Referral   5972
11              Social            Facebook   3811
13              Social            LinkedIn   3790
14              Social                   X   3742
12              Social           Instagram   3723

### Save marketing_attribution.csv

In [81]:
# -------------------------------------------------
# Save marketing attribution dataset
# -------------------------------------------------

marketing_file = (
    RAW_DATA_DIR
    / "marketing_attribution.csv"
)

marketing_attribution_df.to_csv(
    marketing_file,
    index=False
)

print(
    f"Saved: {marketing_file}"
)

print(
    f"Rows: {len(marketing_attribution_df):,}"
)

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\marketing_attribution.csv
Rows: 100,000

## Generate support_tickets.csv

### Prepare user support profile

In [82]:
# -------------------------------------------------
# Prepare user support profile
# -------------------------------------------------

support_rng = np.random.default_rng(SEED + 1000)

support_user_df = (
    user_behavior_df[
        [
            "user_id",
            "engagement_segment",
            "plan_id",
            "subscription_status"
        ]
    ]
    .copy()
)

support_user_df["plan_id"] = (
    support_user_df["plan_id"]
    .fillna("P001")
)

support_user_df.head()

   user_id engagement_segment plan_id subscription_status
0  U000001             Medium    P002              Active
1  U000002            Dormant    P001           Cancelled
2  U000003             Medium    P002              Active
3  U000004             Medium    P001                 NaN
4  U000005             Medium    P001                 NaN

### Decide how many support tickets each user creates

In [83]:
# -------------------------------------------------
# Generate ticket count per user
# -------------------------------------------------

support_lambda_by_plan = {
    "P001": 0.18,
    "P002": 0.38,
    "P003": 0.65
}

support_user_df["ticket_lambda"] = (
    support_user_df["plan_id"]
    .map(support_lambda_by_plan)
    .fillna(0.18)
)

# Cancelled / expired users tend to have slightly
# more support interactions in this simulation
churn_related_mask = (
    support_user_df[
        "subscription_status"
    ].isin(
        ["Cancelled", "Expired"]
    )
)

support_user_df.loc[
    churn_related_mask,
    "ticket_lambda"
] *= 1.35

support_user_df["ticket_count"] = (
    support_rng.poisson(
        support_user_df[
            "ticket_lambda"
        ].to_numpy()
    )
)

print(
    "Expected support tickets:",
    f"{support_user_df['ticket_count'].sum():,}"
)

Expected support tickets: 27,745

### Expand users into ticket rows

In [84]:
# -------------------------------------------------
# Expand users into support ticket records
# -------------------------------------------------

ticket_counts = (
    support_user_df[
        "ticket_count"
    ].to_numpy()
)

support_user_indexes = np.repeat(
    np.arange(
        len(support_user_df)
    ),
    ticket_counts
)

N_TICKETS = len(
    support_user_indexes
)

print(
    "Generating tickets:",
    f"{N_TICKETS:,}"
)

Generating tickets: 27,745

### Define ticket categories

In [85]:
# -------------------------------------------------
# Define support categories and priorities
# -------------------------------------------------

ticket_categories = [
    "Billing",
    "Product Issue",
    "Account",
    "Feature Request",
    "Integration",
    "Performance",
    "Security"
]

category_probabilities = [
    0.18,
    0.27,
    0.14,
    0.15,
    0.11,
    0.10,
    0.05
]

ticket_priorities = [
    "Low",
    "Medium",
    "High",
    "Critical"
]

### Generate ticket creation dates

In [86]:
# -------------------------------------------------
# Generate ticket creation timestamps
# -------------------------------------------------

ticket_user_ids = (
    support_user_df[
        "user_id"
    ]
    .to_numpy()[
        support_user_indexes
    ]
)

ticket_user_lookup = (
    users_df
    .set_index("user_id")[
        "registration_timestamp"
    ]
)

ticket_registration_dates = (
    pd.to_datetime(
        pd.Series(
            ticket_user_ids
        ).map(
            ticket_user_lookup
        )
    )
)

days_available = (
    CURRENT_DATE
    -
    ticket_registration_dates.dt.normalize()
).dt.days.clip(
    lower=0
)

ticket_day_offsets = (
    support_rng.random(
        N_TICKETS
    )
    *
    (days_available + 1)
).astype(int)

ticket_seconds = support_rng.integers(
    0,
    24 * 60 * 60,
    size=N_TICKETS
)

created_timestamps = (
    ticket_registration_dates.dt.normalize()
    +
    pd.to_timedelta(
        ticket_day_offsets,
        unit="D"
    )
    +
    pd.to_timedelta(
        ticket_seconds,
        unit="s"
    )
)

### Generate category and priority

In [87]:
# -------------------------------------------------
# Generate ticket category and priority
# -------------------------------------------------

generated_categories = support_rng.choice(
    ticket_categories,
    size=N_TICKETS,
    p=category_probabilities
)

generated_priorities = support_rng.choice(
    ticket_priorities,
    size=N_TICKETS,
    p=[
        0.32,
        0.46,
        0.18,
        0.04
    ]
)

### Generate resolution times

In [88]:
# -------------------------------------------------
# Generate resolution time
# -------------------------------------------------

resolution_ranges = {
    "Low": (4, 72),
    "Medium": (2, 48),
    "High": (1, 24),
    "Critical": (0.5, 8)
}

resolution_hours = np.zeros(
    N_TICKETS
)

for priority in ticket_priorities:

    priority_mask = (
        generated_priorities
        == priority
    )

    low, high = (
        resolution_ranges[
            priority
        ]
    )

    resolution_hours[
        priority_mask
    ] = support_rng.uniform(
        low,
        high,
        size=priority_mask.sum()
    )

resolution_hours = np.round(
    resolution_hours,
    2
)

### Generate ticket status

In [89]:
# -------------------------------------------------
# Generate ticket status
# -------------------------------------------------

ticket_statuses = support_rng.choice(
    [
        "Open",
        "In Progress",
        "Resolved",
        "Closed"
    ],
    size=N_TICKETS,
    p=[
        0.05,
        0.07,
        0.38,
        0.50
    ]
)

resolved_mask = np.isin(
    ticket_statuses,
    [
        "Resolved",
        "Closed"
    ]
)

### Calculate resolved timestamps

In [90]:
# -------------------------------------------------
# Generate resolved timestamps
# -------------------------------------------------

resolved_timestamps = pd.Series(
    pd.NaT,
    index=np.arange(N_TICKETS),
    dtype="datetime64[ns]"
)

resolved_timestamps.loc[
    resolved_mask
] = (
    created_timestamps.loc[
        resolved_mask
    ]
    +
    pd.to_timedelta(
        resolution_hours[
            resolved_mask
        ],
        unit="h"
    )
)

### Customer satisfaction

In [91]:
# -------------------------------------------------
# Generate satisfaction scores
# -------------------------------------------------

satisfaction_scores = np.full(
    N_TICKETS,
    np.nan
)

for i in np.where(
    resolved_mask
)[0]:

    hours = resolution_hours[i]

    if hours <= 8:
        probabilities = [
            0.02,
            0.05,
            0.13,
            0.35,
            0.45
        ]

    elif hours <= 24:
        probabilities = [
            0.05,
            0.10,
            0.25,
            0.38,
            0.22
        ]

    else:
        probabilities = [
            0.14,
            0.22,
            0.32,
            0.22,
            0.10
        ]

    satisfaction_scores[i] = (
        support_rng.choice(
            [1, 2, 3, 4, 5],
            p=probabilities
        )
    )

### Build the table

In [92]:
# -------------------------------------------------
# Build support tickets table
# -------------------------------------------------

support_tickets_df = pd.DataFrame({
    "ticket_id": [
        f"TKT{str(i).zfill(6)}"
        for i in range(
            1,
            N_TICKETS + 1
        )
    ],
    "user_id": ticket_user_ids,
    "ticket_category":
        generated_categories,
    "priority":
        generated_priorities,
    "created_timestamp":
        created_timestamps,
    "resolved_timestamp":
        resolved_timestamps,
    "ticket_status":
        ticket_statuses,
    "satisfaction_score":
        satisfaction_scores,
    "resolution_time_hours":
        np.where(
            resolved_mask,
            resolution_hours,
            np.nan
        )
})

support_tickets_df.head()

,ticket_id,user_id,ticket_category,priority,created_timestamp,resolved_timestamp,ticket_status,satisfaction_score,resolution_time_hours
0,TKT000001,U000012,Feature Request,Medium,2026-08-22 19:34:29,2026-08-23 23:05:41,Resolved,3.0,27.52
1,TKT000002,U000012,Product Issue,High,2026-08-28 12:16:06,2026-08-29 09:02:18,Closed,5.0,20.77
2,TKT000003,U000014,Feature Request,Medium,2026-03-27 19:46:27,2026-03-28 07:44:39,Closed,5.0,11.97
3,TKT000004,U000018,Product Issue,Low,2025-07-15 19:14:33,NaT,In Progress,NaN,NaN
4,TKT000005,U000025,Product Issue,Medium,2024-07-19 06:40:01,2024-07-20 09:19:01,Resolved,4.0,26.65

### Validate

In [93]:
# -------------------------------------------------
# Validate support ticket dataset
# -------------------------------------------------

print(
    "Total tickets:",
    f"{len(support_tickets_df):,}"
)

print(
    "Unique ticket IDs:",
    support_tickets_df[
        "ticket_id"
    ].nunique()
)

print(
    "Invalid user references:",
    (
        ~support_tickets_df[
            "user_id"
        ].isin(
            users_df["user_id"]
        )
    ).sum()
)

print(
    "Resolved before created:",
    (
        support_tickets_df[
            "resolved_timestamp"
        ].notna()
        &
        (
            support_tickets_df[
                "resolved_timestamp"
            ]
            <
            support_tickets_df[
                "created_timestamp"
            ]
        )
    ).sum()
)

print(
    "Invalid satisfaction scores:",
    (
        support_tickets_df[
            "satisfaction_score"
        ].dropna()
        .lt(1)
        |
        support_tickets_df[
            "satisfaction_score"
        ].dropna()
        .gt(5)
    ).sum()
)

Total tickets: 27,745
Unique ticket IDs: 27745
Invalid user references: 0
Resolved before created: 0
Invalid satisfaction scores: 0

### Inspect ticket distribution

In [94]:
print(
    support_tickets_df[
        "ticket_category"
    ]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print()

print(
    support_tickets_df[
        "priority"
    ]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

ticket_category
Product Issue      26.99
Billing            18.11
Feature Request    14.87
Account            13.71
Integration        11.00
Performance        10.17
Security            5.14
Name: proportion, dtype: float64

priority
Medium      46.08
Low         31.88
High        17.93
Critical     4.11
Name: proportion, dtype: float64

### Save

In [95]:
# -------------------------------------------------
# Save support tickets
# -------------------------------------------------

support_tickets_file = (
    RAW_DATA_DIR
    / "support_tickets.csv"
)

support_tickets_df.to_csv(
    support_tickets_file,
    index=False
)

print(
    f"Saved: {support_tickets_file}"
)

print(
    f"Rows: {len(support_tickets_df):,}"
)

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\support_tickets.csv
Rows: 27,745

## Generate experiment_assignments.csv

### Get eligible users for EXP001

In [96]:
# -------------------------------------------------
# Prepare eligible users for EXP001
# -------------------------------------------------

experiment_rng = np.random.default_rng(SEED + 1100)

exp001_start = pd.Timestamp("2026-04-01")
exp001_end = pd.Timestamp("2026-05-31 23:59:59")

eligible_exp001_users = users_df[
    (
        pd.to_datetime(
            users_df["registration_timestamp"]
        ) >= exp001_start
    )
    &
    (
        pd.to_datetime(
            users_df["registration_timestamp"]
        ) <= exp001_end
    )
].copy()

print(
    "Eligible EXP001 users:",
    f"{len(eligible_exp001_users):,}"
)

Eligible EXP001 users: 6,151

### Assign Control or Treatment

In [97]:
# -------------------------------------------------
# Assign EXP001 experiment groups
# -------------------------------------------------

eligible_exp001_users[
    "experiment_group"
] = experiment_rng.choice(
    ["Control", "Treatment"],
    size=len(eligible_exp001_users),
    p=[0.50, 0.50]
)

eligible_exp001_users[
    "experiment_group"
].value_counts()

experiment_group
Treatment    3103
Control      3048
Name: count, dtype: int64

### Generate assignment/exposure timestamps

In [98]:
# -------------------------------------------------
# Generate assignment and exposure timestamps
# -------------------------------------------------

registration_ts = pd.to_datetime(
    eligible_exp001_users[
        "registration_timestamp"
    ]
)

assignment_delay_minutes = (
    experiment_rng.integers(
        0,
        60,
        size=len(
            eligible_exp001_users
        )
    )
)

eligible_exp001_users[
    "assigned_timestamp"
] = (
    registration_ts
    +
    pd.to_timedelta(
        assignment_delay_minutes,
        unit="m"
    )
)

exposure_delay_minutes = (
    experiment_rng.integers(
        1,
        180,
        size=len(
            eligible_exp001_users
        )
    )
)

eligible_exp001_users[
    "exposure_timestamp"
] = (
    eligible_exp001_users[
        "assigned_timestamp"
    ]
    +
    pd.to_timedelta(
        exposure_delay_minutes,
        unit="m"
    )
)

### Build experiment_assignments_df

In [99]:
# -------------------------------------------------
# Build experiment assignments table
# -------------------------------------------------

experiment_assignments_df = pd.DataFrame({
    "experiment_id": "EXP001",
    "user_id":
        eligible_exp001_users[
            "user_id"
        ].values,
    "experiment_group":
        eligible_exp001_users[
            "experiment_group"
        ].values,
    "assigned_timestamp":
        eligible_exp001_users[
            "assigned_timestamp"
        ].values,
    "exposure_timestamp":
        eligible_exp001_users[
            "exposure_timestamp"
        ].values
})

experiment_assignments_df.insert(
    0,
    "assignment_id",
    [
        f"ASN{str(i).zfill(7)}"
        for i in range(
            1,
            len(
                experiment_assignments_df
            ) + 1
        )
    ]
)

experiment_assignments_df.head()

,assignment_id,experiment_id,user_id,experiment_group,assigned_timestamp,exposure_timestamp
0,ASN0000001,EXP001,U000021,Control,2026-04-26 00:56:00,2026-04-26 01:39:00
1,ASN0000002,EXP001,U000043,Control,2026-04-07 00:36:00,2026-04-07 02:33:00
2,ASN0000003,EXP001,U000057,Control,2026-04-02 00:19:00,2026-04-02 01:56:00
3,ASN0000004,EXP001,U000102,Treatment,2026-04-13 00:49:00,2026-04-13 03:00:00
4,ASN0000005,EXP001,U000110,Treatment,2026-05-16 00:18:00,2026-05-16 01:46:00

### Validate the experiment assignment rules

In [100]:
# -------------------------------------------------
# Validate experiment assignments
# -------------------------------------------------

print(
    "Total assignments:",
    f"{len(experiment_assignments_df):,}"
)

print(
    "Unique assignment IDs:",
    experiment_assignments_df[
        "assignment_id"
    ].nunique()
)

print(
    "Invalid user references:",
    (
        ~experiment_assignments_df[
            "user_id"
        ].isin(
            users_df["user_id"]
        )
    ).sum()
)

print(
    "Invalid experiment references:",
    (
        ~experiment_assignments_df[
            "experiment_id"
        ].isin(
            experiments_df[
                "experiment_id"
            ]
        )
    ).sum()
)

print(
    "Duplicate user-experiment pairs:",
    experiment_assignments_df[
        [
            "experiment_id",
            "user_id"
        ]
    ].duplicated().sum()
)

Total assignments: 6,151
Unique assignment IDs: 6151
Invalid user references: 0
Invalid experiment references: 0
Duplicate user-experiment pairs: 0

### Check Control/Treatment balance

In [101]:
(
    experiment_assignments_df[
        "experiment_group"
    ]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

experiment_group
Treatment    50.45
Control      49.55
Name: proportion, dtype: float64

### Save

In [102]:
# -------------------------------------------------
# Save experiment assignments
# -------------------------------------------------

experiment_assignments_file = (
    RAW_DATA_DIR
    / "experiment_assignments.csv"
)

experiment_assignments_df.to_csv(
    experiment_assignments_file,
    index=False
)

print(
    f"Saved: {experiment_assignments_file}"
)

print(
    f"Rows: {len(experiment_assignments_df):,}"
)

Saved: c:\New folder\Hands on Projects\Data-Analysis\saas-product-growth-experimentation-analytics\data\raw\experiment_assignments.csv
Rows: 6,151