In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
RAW_DATA_PATH = Path("../data/raw")

print("Raw data folder:")
print(RAW_DATA_PATH.resolve())

Raw data folder:
C:\New folder\Hands on Projects\healthcare-operations-population-health-analytics\data\raw

In [3]:
raw_files = list(RAW_DATA_PATH.glob("*.csv"))

print("CSV files found:", len(raw_files))

for file in raw_files:
    print(file.name)

CSV files found: 12
admissions.csv
appointments.csv
departments.csv
diagnoses.csv
encounters.csv
encounter_diagnoses.csv
encounter_procedures.csv
lab_results.csv
patients.csv
payers.csv
procedures.csv
providers.csv

In [4]:
patients = pd.read_csv(RAW_DATA_PATH / "patients.csv")
providers = pd.read_csv(RAW_DATA_PATH / "providers.csv")
departments = pd.read_csv(RAW_DATA_PATH / "departments.csv")
payers = pd.read_csv(RAW_DATA_PATH / "payers.csv")
diagnoses = pd.read_csv(RAW_DATA_PATH / "diagnoses.csv")
procedures = pd.read_csv(RAW_DATA_PATH / "procedures.csv")
encounters = pd.read_csv(RAW_DATA_PATH / "encounters.csv")
encounter_diagnoses = pd.read_csv(RAW_DATA_PATH / "encounter_diagnoses.csv")
encounter_procedures = pd.read_csv(RAW_DATA_PATH / "encounter_procedures.csv")
admissions = pd.read_csv(RAW_DATA_PATH / "admissions.csv")
appointments = pd.read_csv(RAW_DATA_PATH / "appointments.csv")
lab_results = pd.read_csv(RAW_DATA_PATH / "lab_results.csv")

print("All raw datasets loaded successfully.")

All raw datasets loaded successfully.

In [5]:
datasets = {
    "patients": patients,
    "providers": providers,
    "departments": departments,
    "payers": payers,
    "diagnoses": diagnoses,
    "procedures": procedures,
    "encounters": encounters,
    "encounter_diagnoses": encounter_diagnoses,
    "encounter_procedures": encounter_procedures,
    "admissions": admissions,
    "appointments": appointments,
    "lab_results": lab_results
}

In [6]:
source_inventory = []

for table_name, df in datasets.items():
    source_inventory.append({
        "Table": table_name,
        "Rows": len(df),
        "Columns": len(df.columns)
    })

source_inventory_df = pd.DataFrame(source_inventory)

source_inventory_df

                   Table    Rows  Columns
0               patients   10000        9
1              providers     120        6
2            departments      25        6
3                 payers       6        3
4              diagnoses      50        5
5             procedures      40        5
6             encounters   90000       13
7    encounter_diagnoses  153595        5
8   encounter_procedures   70419        5
9             admissions   17740       11
10          appointments   50000        9
11           lab_results  100000       10

In [7]:
total_records = source_inventory_df["Rows"].sum()

print(
    "Total records across all raw sources:",
    f"{total_records:,}"
)

Total records across all raw sources: 491,995

In [8]:
patients.head()

,PatientID,BirthDate,Gender,Race,Ethnicity,ZipCode,State,Region,RegistrationDate
0,PAT000001,24-07-2006,Male,White,Not Hispanic or Latino,22554,VA,Northern,12-08-2023
1,PAT000002,07-04-1953,Female,White,Not Hispanic or Latino,23834,VA,Southern,15-10-2023
2,PAT000003,09-03-1994,Male,White,Not Hispanic or Latino,23606,VA,Eastern,26-05-2024
3,PAT000004,26-08-2023,Female,Black or African American,Not Hispanic or Latino,22401,VA,Northern,16-10-2023
4,PAT000005,25-02-2007,Female,White,Hispanic or Latino,23805,VA,Southern,07-12-2023

In [9]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         10000 non-null  str
 1   BirthDate         10000 non-null  str
 2   Gender            10000 non-null  str
 3   Race              10000 non-null  str
 4   Ethnicity         10000 non-null  str
 5   ZipCode           10000 non-null  int64
 6   State             10000 non-null  str
 7   Region            9900 non-null   str
 8   RegistrationDate  10000 non-null  str
dtypes: int64(1), str(8)
memory usage: 703.3 KB

In [10]:
patients.sample(10)

,PatientID,BirthDate,Gender,Race,Ethnicity,ZipCode,State,Region,RegistrationDate
727,PAT000728,13-03-1997,Male,White,Hispanic or Latino,23221,VA,Central,03-06-2023
849,PAT000850,08-12-1980,Male,Multiple,Hispanic or Latino,23834,VA,Southern,09-12-2024
6940,PAT006941,05-10-2019,Male,White,Not Hispanic or Latino,22551,VA,Northern,15-12-2025
7863,PAT007864,24-03-2019,Male,Asian,Not Hispanic or Latino,22401,VA,Northern,22-05-2024
6279,PAT006280,22-12-1995,Female,Black or African American,Unknown,23221,VA,Central,12-07-2023
5120,PAT005121,12-01-2017,Male,Asian,Not Hispanic or Latino,23220,VA,Central,10-12-2025
4470,PAT004471,10-07-1995,Other,White,Not Hispanic or Latino,22551,VA,Northern,08-01-2024
1194,PAT001195,24-11-1979,Female,White,Hispanic or Latino,23223,VA,Central,08-11-2023
565,PAT000566,20-12-2025,Male,Black or African American,Not Hispanic or Latino,22902,VA,Western,27-12-2025
2297,PAT002298,09-02-1955,Female,Multiple,Not Hispanic or Latino,23602,VA,Eastern,24-12-2024

In [11]:
for table_name, df in datasets.items():
    print("\n", "=" * 50)
    print(table_name.upper())
    print("=" * 50)
    print(df.columns.tolist())

 ==================================================
PATIENTS
==================================================
['PatientID', 'BirthDate', 'Gender', 'Race', 'Ethnicity', 'ZipCode', 'State', 'Region', 'RegistrationDate']

 ==================================================
PROVIDERS
==================================================
['ProviderID', 'DepartmentID', 'ProviderType', 'Specialty', 'HireDate', 'ActiveFlag']

 ==================================================
DEPARTMENTS
==================================================
['DepartmentID', 'DepartmentName', 'FacilityName', 'DepartmentType', 'City', 'State']

 ==================================================
PAYERS
==================================================
['PayerID', 'PayerName', 'PayerType']

 ==================================================
DIAGNOSES
==================================================
['DiagnosisID', 'DiagnosisCode', 'DiagnosisName', 'DiagnosisCategory', 'ChronicConditionFlag']

 ==================================================
PROCEDURES
==================================================
['ProcedureID', 'ProcedureCode', 'ProcedureName', 'ProcedureCategory', 'StandardCost']

 ==================================================
ENCOUNTERS
==================================================
['EncounterID', 'PatientID', 'ProviderID', 'DepartmentID', 'PayerID', 'EncounterDate', 'EncounterType', 'ArrivalDateTime', 'TriageDateTime', 'ProviderStartDateTime', 'EncounterEndDateTime', 'EncounterStatus', 'EncounterCost']

 ==================================================
ENCOUNTER_DIAGNOSES
==================================================
['EncounterDiagnosisID', 'EncounterID', 'DiagnosisID', 'DiagnosisType', 'PresentOnAdmissionFlag']

 ==================================================
ENCOUNTER_PROCEDURES
==================================================
['EncounterProcedureID', 'EncounterID', 'ProcedureID', 'ProcedureDate', 'ProcedureCost']

 ==================================================
ADMISSIONS
==================================================
['AdmissionID', 'EncounterID', 'PatientID', 'DepartmentID', 'AdmissionDateTime', 'DischargeDateTime', 'AdmissionType', 'DischargeDisposition', 'FollowUpRequiredFlag', 'FollowUpCompletedFlag', 'FollowUpDate']

 ==================================================
APPOINTMENTS
==================================================
['AppointmentID', 'PatientID', 'ProviderID', 'DepartmentID', 'ScheduledDate', 'AppointmentDateTime', 'AppointmentStatus', 'AppointmentType', 'CancellationReason']

 ==================================================
LAB_RESULTS
==================================================
['LabResultID', 'EncounterID', 'PatientID', 'LabTest', 'ResultValue', 'ResultUnit', 'ReferenceLow', 'ReferenceHigh', 'ResultFlag', 'ResultDateTime']

In [12]:
completeness_records = []

for table_name, df in datasets.items():

    total_rows = len(df)

    for column in df.columns:

        missing_count = df[column].isna().sum()

        missing_pct = (
            missing_count / total_rows * 100
            if total_rows > 0
            else 0
        )

        completeness_records.append({
            "Table": table_name,
            "Column": column,
            "TotalRows": total_rows,
            "MissingCount": missing_count,
            "MissingPercent": round(missing_pct, 2)
        })

completeness_df = pd.DataFrame(
    completeness_records
)

completeness_df.head(20)

          Table            Column  TotalRows  MissingCount  MissingPercent
0      patients         PatientID      10000             0             0.0
1      patients         BirthDate      10000             0             0.0
2      patients            Gender      10000             0             0.0
3      patients              Race      10000             0             0.0
4      patients         Ethnicity      10000             0             0.0
5      patients           ZipCode      10000             0             0.0
6      patients             State      10000             0             0.0
7      patients            Region      10000           100             1.0
8      patients  RegistrationDate      10000             0             0.0
9     providers        ProviderID        120             0             0.0
10    providers      DepartmentID        120             0             0.0
11    providers      ProviderType        120             0             0.0
12    providers         Specialty        120             0             0.0
13    providers          HireDate        120             0             0.0
14    providers        ActiveFlag        120             0             0.0
15  departments      DepartmentID         25             0             0.0
16  departments    DepartmentName         25             0             0.0
17  departments      FacilityName         25             0             0.0
18  departments    DepartmentType         25             0             0.0
19  departments              City         25             0             0.0

In [13]:
missing_values_df = (
    completeness_df[
        completeness_df["MissingCount"] > 0
    ]
    .sort_values(
        ["MissingPercent", "MissingCount"],
        ascending=False
    )
    .reset_index(drop=True)
)

missing_values_df

,Table,Column,TotalRows,MissingCount,MissingPercent
0,appointments,CancellationReason,50000,45003,90.01
1,encounter_diagnoses,PresentOnAdmissionFlag,153595,123378,80.33
2,encounters,TriageDateTime,90000,58229,64.70
3,admissions,FollowUpDate,17740,8336,46.99
4,encounters,ProviderID,90000,1401,1.56
5,patients,Region,10000,100,1.00
6,appointments,ProviderID,50000,400,0.80
7,lab_results,ResultUnit,100000,700,0.70
8,admissions,DischargeDateTime,17740,124,0.70
9,encounters,ProviderStartDateTime,90000,501,0.56

In [14]:
missing_values_df.head(30)

,Table,Column,TotalRows,MissingCount,MissingPercent
0,appointments,CancellationReason,50000,45003,90.01
1,encounter_diagnoses,PresentOnAdmissionFlag,153595,123378,80.33
2,encounters,TriageDateTime,90000,58229,64.70
3,admissions,FollowUpDate,17740,8336,46.99
4,encounters,ProviderID,90000,1401,1.56
5,patients,Region,10000,100,1.00
6,appointments,ProviderID,50000,400,0.80
7,lab_results,ResultUnit,100000,700,0.70
8,admissions,DischargeDateTime,17740,124,0.70
9,encounters,ProviderStartDateTime,90000,501,0.56

In [15]:
for table_name in datasets.keys():

    table_missing = missing_values_df[
        missing_values_df["Table"] == table_name
    ]

    if len(table_missing) > 0:

        print("\n", "=" * 60)
        print(table_name.upper())
        print("=" * 60)

        print(
            table_missing[
                [
                    "Column",
                    "MissingCount",
                    "MissingPercent"
                ]
            ].to_string(index=False)
        )

 ============================================================
PATIENTS
============================================================
Column  MissingCount  MissingPercent
Region           100             1.0

 ============================================================
ENCOUNTERS
============================================================
               Column  MissingCount  MissingPercent
       TriageDateTime         58229           64.70
           ProviderID          1401            1.56
ProviderStartDateTime           501            0.56

 ============================================================
ENCOUNTER_DIAGNOSES
============================================================
                Column  MissingCount  MissingPercent
PresentOnAdmissionFlag        123378           80.33

 ============================================================
ADMISSIONS
============================================================
           Column  MissingCount  MissingPercent
     FollowUpDate          8336           46.99
DischargeDateTime           124            0.70

 ============================================================
APPOINTMENTS
============================================================
            Column  MissingCount  MissingPercent
CancellationReason         45003           90.01
        ProviderID           400            0.80

 ============================================================
LAB_RESULTS
============================================================
    Column  MissingCount  MissingPercent
ResultUnit           700             0.7

In [16]:
missing_values_df[
    missing_values_df["Table"] == "patients"
]

      Table  Column  TotalRows  MissingCount  MissingPercent
5  patients  Region      10000           100             1.0

In [17]:
missing_values_df[
    missing_values_df["Table"] == "encounters"
]

        Table                 Column  TotalRows  MissingCount  MissingPercent
2  encounters         TriageDateTime      90000         58229           64.70
4  encounters             ProviderID      90000          1401            1.56
9  encounters  ProviderStartDateTime      90000           501            0.56

In [18]:
missing_values_df[
    missing_values_df["Table"] == "appointments"
]

          Table              Column  TotalRows  MissingCount  MissingPercent
0  appointments  CancellationReason      50000         45003           90.01
6  appointments          ProviderID      50000           400            0.80

In [19]:
missing_values_df[
    missing_values_df["Table"] == "lab_results"
]

         Table      Column  TotalRows  MissingCount  MissingPercent
7  lab_results  ResultUnit     100000           700             0.7

In [20]:
missing_summary_by_table = (
    completeness_df
    .groupby("Table")
    .agg(
        TotalMissingValues=(
            "MissingCount",
            "sum"
        ),
        ColumnsWithMissing=(
            "MissingCount",
            lambda x: (x > 0).sum()
        )
    )
    .reset_index()
    .sort_values(
        "TotalMissingValues",
        ascending=False
    )
)

missing_summary_by_table

                   Table  TotalMissingValues  ColumnsWithMissing
4    encounter_diagnoses              123378                   1
6             encounters               60131                   3
1           appointments               45403                   2
0             admissions                8460                   2
7            lab_results                 700                   1
8               patients                 100                   1
3              diagnoses                   0                   0
2            departments                   0                   0
5   encounter_procedures                   0                   0
9                 payers                   0                   0
10            procedures                   0                   0
11             providers                   0                   0

In [21]:
PROFILING_PATH = Path(
    "../data/profiling"
)

PROFILING_PATH.mkdir(
    parents=True,
    exist_ok=True
)

In [22]:
completeness_df.to_csv(
    PROFILING_PATH
    / "completeness_profile.csv",
    index=False
)

print(
    "Completeness profile saved successfully."
)

Completeness profile saved successfully.

In [23]:
primary_keys = {
    "patients": "PatientID",
    "providers": "ProviderID",
    "departments": "DepartmentID",
    "payers": "PayerID",
    "diagnoses": "DiagnosisID",
    "procedures": "ProcedureID",
    "encounters": "EncounterID",
    "encounter_diagnoses": "EncounterDiagnosisID",
    "encounter_procedures": "EncounterProcedureID",
    "admissions": "AdmissionID",
    "appointments": "AppointmentID",
    "lab_results": "LabResultID"
}

In [24]:
pk_profile_records = []

for table_name, pk_column in primary_keys.items():

    df = datasets[table_name]

    duplicate_pk_count = df[pk_column].duplicated().sum()
    missing_pk_count = df[pk_column].isna().sum()

    pk_profile_records.append({
        "Table": table_name,
        "PrimaryKey": pk_column,
        "Rows": len(df),
        "MissingPKCount": missing_pk_count,
        "DuplicatePKCount": duplicate_pk_count,
        "UniquePKCount": df[pk_column].nunique(dropna=True)
    })

pk_profile_df = pd.DataFrame(
    pk_profile_records
)

pk_profile_df

,Table,PrimaryKey,Rows,MissingPKCount,DuplicatePKCount,UniquePKCount
0,patients,PatientID,10000,0,20,9980
1,providers,ProviderID,120,0,0,120
2,departments,DepartmentID,25,0,0,25
3,payers,PayerID,6,0,0,6
4,diagnoses,DiagnosisID,50,0,0,50
5,procedures,ProcedureID,40,0,0,40
6,encounters,EncounterID,90000,0,0,90000
7,encounter_diagnoses,EncounterDiagnosisID,153595,0,0,153595
8,encounter_procedures,EncounterProcedureID,70419,0,0,70419
9,admissions,AdmissionID,17740,0,0,17740
10,appointments,AppointmentID,50000,0,0,50000
11,lab_results,LabResultID,100000,0,0,100000

In [25]:
pk_issues_df = pk_profile_df[
    (pk_profile_df["MissingPKCount"] > 0)
    |
    (pk_profile_df["DuplicatePKCount"] > 0)
].copy()

pk_issues_df

      Table PrimaryKey   Rows  MissingPKCount  DuplicatePKCount  UniquePKCount
0  patients  PatientID  10000               0                20           9980

In [26]:
duplicate_patient_ids = patients[
    patients["PatientID"].duplicated(
        keep=False
    )
].sort_values(
    "PatientID"
)

duplicate_patient_ids.head(20)

,PatientID,BirthDate,Gender,Race,Ethnicity,ZipCode,State,Region,RegistrationDate
317,PAT000318,05-12-2018,Male,Black or African American,Hispanic or Latino,22554,VA,Northern,29-05-2025
371,PAT000318,02-12-2005,Female,White,Not Hispanic or Latino,23805,VA,Southern,19-06-2025
6903,PAT000667,28-02-1985,Male,Asian,Not Hispanic or Latino,23223,VA,Central,03-10-2025
666,PAT000667,28-04-1975,Male,Asian,Not Hispanic or Latino,23834,VA,Southern,01-02-2025
892,PAT000893,09-12-2007,Male,Other,Not Hispanic or Latino,23601,VA,Eastern,26-06-2025
8050,PAT000893,08-08-1998,Unknown,Asian,Not Hispanic or Latino,23221,VA,Central,31-03-2023
5147,PAT000928,08-10-1969,Female,Black or African American,Not Hispanic or Latino,23803,VA,Southern,21-06-2025
927,PAT000928,22-05-2003,Male,White,Not Hispanic or Latino,22903,VA,Western,23-01-2023
6944,PAT001829,20-07-2010,Female,Other,Not Hispanic or Latino,23223,VA,Central,31-07-2024
1828,PAT001829,12-08-1972,Male,Black or African American,Not Hispanic or Latino,23185,VA,Eastern,28-07-2024
1925,PAT001926,04-03-1989,Female,Black or African American,Not Hispanic or Latino,23601,VA,Eastern,07-03-2023
3595,PAT001926,21-01-2006,Male,White,Not Hispanic or Latino,23602,VA,Eastern,03-12-2024
1930,PAT001931,13-07-1985,Male,Multiple,Not Hispanic or Latino,22902,VA,Western,15-08-2023
8718,PAT001931,15-11-2007,Female,Black or African American,Not Hispanic or Latino,23606,VA,Eastern,12-07-2024
5685,PAT002408,15-08-1969,Female,White,Not Hispanic or Latino,23220,VA,Central,12-02-2025
2407,PAT002408,13-06-1970,Male,White,Not Hispanic or Latino,22401,VA,Northern,03-10-2024
4183,PAT002479,03-02-1985,Male,American Indian or Alaska Native,Not Hispanic or Latino,23225,VA,Central,10-06-2023
2478,PAT002479,23-02-2003,Male,White,Not Hispanic or Latino,23831,VA,Southern,20-10-2023
3271,PAT003272,25-05-1992,Male,White,Not Hispanic or Latino,22551,VA,Northern,03-10-2024
227,PAT003272,04-12-1963,Male,White,Not Hispanic or Latino,22902,VA,Western,30-05-2025

In [27]:
duplicate_patient_ids[
    "PatientID"
].value_counts().head(20)

PatientID
PAT000318    2
PAT000667    2
PAT000893    2
PAT000928    2
PAT001829    2
PAT001926    2
PAT001931    2
PAT002408    2
PAT002479    2
PAT003272    2
PAT003484    2
PAT004375    2
PAT005116    2
PAT005177    2
PAT006727    2
PAT007035    2
PAT007631    2
PAT007822    2
PAT009363    2
PAT009434    2
Name: count, dtype: int64

In [28]:
example_duplicate_patient_id = (
    duplicate_patient_ids[
        "PatientID"
    ].iloc[0]
)

patients[
    patients["PatientID"]
    == example_duplicate_patient_id
]

,PatientID,BirthDate,Gender,Race,Ethnicity,ZipCode,State,Region,RegistrationDate
317,PAT000318,05-12-2018,Male,Black or African American,Hispanic or Latino,22554,VA,Northern,29-05-2025
371,PAT000318,02-12-2005,Female,White,Not Hispanic or Latino,23805,VA,Southern,19-06-2025

In [29]:
full_row_duplicate_records = []

for table_name, df in datasets.items():

    duplicate_row_count = df.duplicated().sum()

    full_row_duplicate_records.append({
        "Table": table_name,
        "DuplicateFullRows": duplicate_row_count
    })

full_row_duplicates_df = pd.DataFrame(
    full_row_duplicate_records
)

full_row_duplicates_df

                   Table  DuplicateFullRows
0               patients                  0
1              providers                  0
2            departments                  0
3                 payers                  0
4              diagnoses                  0
5             procedures                  0
6             encounters                  0
7    encounter_diagnoses                  0
8   encounter_procedures                  0
9             admissions                  0
10          appointments                  0
11           lab_results                  0

In [30]:
duplicate_encounter_diagnosis_pairs = (
    encounter_diagnoses
    .duplicated(
        subset=[
            "EncounterID",
            "DiagnosisID"
        ],
        keep=False
    )
)

duplicate_encounter_diagnosis_df = (
    encounter_diagnoses[
        duplicate_encounter_diagnosis_pairs
    ]
    .sort_values(
        [
            "EncounterID",
            "DiagnosisID"
        ]
    )
)

print(
    "Rows involved in duplicate Encounter-Diagnosis pairs:",
    len(duplicate_encounter_diagnosis_df)
)

print(
    "Duplicate business-key occurrences:",
    encounter_diagnoses
    .duplicated(
        subset=[
            "EncounterID",
            "DiagnosisID"
        ]
    )
    .sum()
)

Rows involved in duplicate Encounter-Diagnosis pairs: 918
Duplicate business-key occurrences: 459

In [31]:
encounter_procedure_duplicate_summary = (
    encounter_procedures
    .duplicated(
        subset=[
            "EncounterID",
            "ProcedureID",
            "ProcedureDate"
        ]
    )
    .sum()
)

print(
    "Duplicate Encounter-Procedure-Date combinations:",
    encounter_procedure_duplicate_summary
)

Duplicate Encounter-Procedure-Date combinations: 0

In [32]:
primary_diagnosis_counts = (
    encounter_diagnoses[
        encounter_diagnoses[
            "DiagnosisType"
        ] == "Primary"
    ]
    .groupby("EncounterID")
    .size()
)

multiple_primary_diagnoses = (
    primary_diagnosis_counts[
        primary_diagnosis_counts > 1
    ]
)

print(
    "Encounters with more than one Primary diagnosis:",
    len(multiple_primary_diagnoses)
)

Encounters with more than one Primary diagnosis: 253

In [33]:
duplicate_quality_summary = pd.DataFrame([
    {
        "Check": "PatientID uniqueness",
        "Table": "patients",
        "IssueCount": patients["PatientID"].duplicated().sum(),
        "Severity": "Critical"
    },
    {
        "Check": "Encounter-Diagnosis duplicate business key",
        "Table": "encounter_diagnoses",
        "IssueCount": encounter_diagnoses.duplicated(
            subset=["EncounterID", "DiagnosisID"]
        ).sum(),
        "Severity": "High"
    },
    {
        "Check": "Encounter-Procedure-Date duplicates",
        "Table": "encounter_procedures",
        "IssueCount": encounter_procedures.duplicated(
            subset=[
                "EncounterID",
                "ProcedureID",
                "ProcedureDate"
            ]
        ).sum(),
        "Severity": "Medium"
    },
    {
        "Check": "Multiple Primary diagnoses per encounter",
        "Table": "encounter_diagnoses",
        "IssueCount": len(multiple_primary_diagnoses),
        "Severity": "High"
    }
])

duplicate_quality_summary

,Check,Table,IssueCount,Severity
0,PatientID uniqueness,patients,20,Critical
1,Encounter-Diagnosis duplicate business key,encounter_diagnoses,459,High
2,Encounter-Procedure-Date duplicates,encounter_procedures,0,Medium
3,Multiple Primary diagnoses per encounter,encounter_diagnoses,253,High

In [34]:
pk_profile_df.to_csv(
    PROFILING_PATH / "primary_key_profile.csv",
    index=False
)

In [35]:
duplicate_quality_summary.to_csv(
    PROFILING_PATH / "duplicate_quality_summary.csv",
    index=False
)

In [36]:
dtype_records = []

for table_name, df in datasets.items():
    for column in df.columns:
        dtype_records.append({
            "Table": table_name,
            "Column": column,
            "PandasDataType": str(df[column].dtype)
        })

dtype_profile_df = pd.DataFrame(dtype_records)

dtype_profile_df

          Table          Column PandasDataType
0      patients       PatientID            str
1      patients       BirthDate            str
2      patients          Gender            str
3      patients            Race            str
4      patients       Ethnicity            str
..          ...             ...            ...
82  lab_results      ResultUnit            str
83  lab_results    ReferenceLow        float64
84  lab_results   ReferenceHigh        float64
85  lab_results      ResultFlag            str
86  lab_results  ResultDateTime            str

[87 rows x 3 columns]

In [37]:
object_columns_df = dtype_profile_df[
    dtype_profile_df["PandasDataType"] == "object"
].copy()

object_columns_df

Empty DataFrame
Columns: [Table, Column, PandasDataType]
Index: []

In [38]:
expected_date_columns = {
    "patients": [
        "BirthDate",
        "RegistrationDate"
    ],
    "providers": [
        "HireDate"
    ],
    "encounters": [
        "EncounterDate",
        "ArrivalDateTime",
        "TriageDateTime",
        "ProviderStartDateTime",
        "EncounterEndDateTime"
    ],
    "encounter_procedures": [
        "ProcedureDate"
    ],
    "admissions": [
        "AdmissionDateTime",
        "DischargeDateTime",
        "FollowUpDate"
    ],
    "appointments": [
        "ScheduledDate",
        "AppointmentDateTime"
    ],
    "lab_results": [
        "ResultDateTime"
    ]
}

In [39]:
date_type_profile = []

for table_name, columns in expected_date_columns.items():
    df = datasets[table_name]

    for column in columns:
        date_type_profile.append({
            "Table": table_name,
            "Column": column,
            "CurrentDataType": str(df[column].dtype),
            "ExpectedDataType": "datetime"
        })

date_type_profile_df = pd.DataFrame(
    date_type_profile
)

date_type_profile_df

,Table,Column,CurrentDataType,ExpectedDataType
0,patients,BirthDate,str,datetime
1,patients,RegistrationDate,str,datetime
2,providers,HireDate,str,datetime
3,encounters,EncounterDate,str,datetime
4,encounters,ArrivalDateTime,str,datetime
5,encounters,TriageDateTime,str,datetime
6,encounters,ProviderStartDateTime,str,datetime
7,encounters,EncounterEndDateTime,str,datetime
8,encounter_procedures,ProcedureDate,str,datetime
9,admissions,AdmissionDateTime,str,datetime
10,admissions,DischargeDateTime,str,datetime
11,admissions,FollowUpDate,str,datetime
12,appointments,ScheduledDate,str,datetime
13,appointments,AppointmentDateTime,str,datetime
14,lab_results,ResultDateTime,str,datetime

In [40]:
date_parse_results = []

for table_name, columns in expected_date_columns.items():

    df = datasets[table_name]

    for column in columns:

        converted = pd.to_datetime(
            df[column],
            errors="coerce"
        )

        original_non_null = df[column].notna().sum()
        converted_non_null = converted.notna().sum()

        failed_parse_count = (
            original_non_null
            - converted_non_null
        )

        date_parse_results.append({
            "Table": table_name,
            "Column": column,
            "OriginalNonNull": original_non_null,
            "FailedParseCount": failed_parse_count
        })

date_parse_profile_df = pd.DataFrame(
    date_parse_results
)

date_parse_profile_df

C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\1429032833.py:9: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  converted = pd.to_datetime(
C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\1429032833.py:9: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  converted = pd.to_datetime(
C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\1429032833.py:9: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  converted = pd.to_datetime(
C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\1429032833.py:9: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  converted = pd.to_datetime(
C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\1429032833.py:9: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  converted = pd.to_datetime(
C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\1429032833.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(

,Table,Column,OriginalNonNull,FailedParseCount
0,patients,BirthDate,10000,0
1,patients,RegistrationDate,10000,6112
2,providers,HireDate,120,70
3,encounters,EncounterDate,90000,0
4,encounters,ArrivalDateTime,90000,0
5,encounters,TriageDateTime,31771,0
6,encounters,ProviderStartDateTime,89499,0
7,encounters,EncounterEndDateTime,90000,54023
8,encounter_procedures,ProcedureDate,70419,0
9,admissions,AdmissionDateTime,17740,0
10,admissions,DischargeDateTime,17616,0
11,admissions,FollowUpDate,9404,0
12,appointments,ScheduledDate,50000,0
13,appointments,AppointmentDateTime,50000,0
14,lab_results,ResultDateTime,100000,0

In [41]:
date_parse_issues_df = date_parse_profile_df[
    date_parse_profile_df["FailedParseCount"] > 0
]

date_parse_issues_df

        Table                Column  OriginalNonNull  FailedParseCount
1    patients      RegistrationDate            10000              6112
2   providers              HireDate              120                70
7  encounters  EncounterEndDateTime            90000             54023

In [42]:
numeric_columns = {
    "procedures": [
        "StandardCost"
    ],
    "encounters": [
        "EncounterCost"
    ],
    "encounter_procedures": [
        "ProcedureCost"
    ],
    "lab_results": [
        "ResultValue",
        "ReferenceLow",
        "ReferenceHigh"
    ]
}

In [43]:
numeric_type_profile = []

for table_name, columns in numeric_columns.items():

    df = datasets[table_name]

    for column in columns:

        numeric_type_profile.append({
            "Table": table_name,
            "Column": column,
            "CurrentDataType": str(df[column].dtype),
            "ExpectedType": "numeric"
        })

numeric_type_profile_df = pd.DataFrame(
    numeric_type_profile
)

numeric_type_profile_df

                  Table         Column CurrentDataType ExpectedType
0            procedures   StandardCost         float64      numeric
1            encounters  EncounterCost         float64      numeric
2  encounter_procedures  ProcedureCost         float64      numeric
3           lab_results    ResultValue         float64      numeric
4           lab_results   ReferenceLow         float64      numeric
5           lab_results  ReferenceHigh         float64      numeric

In [44]:
numeric_parse_results = []

for table_name, columns in numeric_columns.items():

    df = datasets[table_name]

    for column in columns:

        converted = pd.to_numeric(
            df[column],
            errors="coerce"
        )

        original_non_null = df[column].notna().sum()
        converted_non_null = converted.notna().sum()

        failed_numeric_parse = (
            original_non_null
            - converted_non_null
        )

        numeric_parse_results.append({
            "Table": table_name,
            "Column": column,
            "FailedNumericParseCount": failed_numeric_parse
        })

numeric_parse_profile_df = pd.DataFrame(
    numeric_parse_results
)

numeric_parse_profile_df

                  Table         Column  FailedNumericParseCount
0            procedures   StandardCost                        0
1            encounters  EncounterCost                        0
2  encounter_procedures  ProcedureCost                        0
3           lab_results    ResultValue                        0
4           lab_results   ReferenceLow                        0
5           lab_results  ReferenceHigh                        0

In [45]:
type_quality_summary = pd.concat(
    [
        date_parse_profile_df.assign(
            IssueType="Date/Datetime Parsing"
        ),
        numeric_parse_profile_df.assign(
            IssueType="Numeric Parsing"
        )
    ],
    ignore_index=True,
    sort=False
)

type_quality_summary

,Table,Column,OriginalNonNull,FailedParseCount,IssueType,FailedNumericParseCount
0,patients,BirthDate,10000.0,0.0,Date/Datetime Parsing,NaN
1,patients,RegistrationDate,10000.0,6112.0,Date/Datetime Parsing,NaN
2,providers,HireDate,120.0,70.0,Date/Datetime Parsing,NaN
3,encounters,EncounterDate,90000.0,0.0,Date/Datetime Parsing,NaN
4,encounters,ArrivalDateTime,90000.0,0.0,Date/Datetime Parsing,NaN
5,encounters,TriageDateTime,31771.0,0.0,Date/Datetime Parsing,NaN
6,encounters,ProviderStartDateTime,89499.0,0.0,Date/Datetime Parsing,NaN
7,encounters,EncounterEndDateTime,90000.0,54023.0,Date/Datetime Parsing,NaN
8,encounter_procedures,ProcedureDate,70419.0,0.0,Date/Datetime Parsing,NaN
9,admissions,AdmissionDateTime,17740.0,0.0,Date/Datetime Parsing,NaN
10,admissions,DischargeDateTime,17616.0,0.0,Date/Datetime Parsing,NaN
11,admissions,FollowUpDate,9404.0,0.0,Date/Datetime Parsing,NaN
12,appointments,ScheduledDate,50000.0,0.0,Date/Datetime Parsing,NaN
13,appointments,AppointmentDateTime,50000.0,0.0,Date/Datetime Parsing,NaN
14,lab_results,ResultDateTime,100000.0,0.0,Date/Datetime Parsing,NaN
15,procedures,StandardCost,NaN,NaN,Numeric Parsing,0.0
16,encounters,EncounterCost,NaN,NaN,Numeric Parsing,0.0
17,encounter_procedures,ProcedureCost,NaN,NaN,Numeric Parsing,0.0
18,lab_results,ResultValue,NaN,NaN,Numeric Parsing,0.0
19,lab_results,ReferenceLow,NaN,NaN,Numeric Parsing,0.0
20,lab_results,ReferenceHigh,NaN,NaN,Numeric Parsing,0.0

In [46]:
dtype_profile_df.to_csv(
    PROFILING_PATH / "data_type_profile.csv",
    index=False
)

date_parse_profile_df.to_csv(
    PROFILING_PATH / "date_parse_profile.csv",
    index=False
)

numeric_parse_profile_df.to_csv(
    PROFILING_PATH / "numeric_parse_profile.csv",
    index=False
)

print("Data type profiling outputs saved.")

Data type profiling outputs saved.

In [47]:
relationship_checks = [
    ("providers", "DepartmentID", "departments", "DepartmentID"),

    ("encounters", "PatientID", "patients", "PatientID"),
    ("encounters", "ProviderID", "providers", "ProviderID"),
    ("encounters", "DepartmentID", "departments", "DepartmentID"),
    ("encounters", "PayerID", "payers", "PayerID"),

    ("encounter_diagnoses", "EncounterID", "encounters", "EncounterID"),
    ("encounter_diagnoses", "DiagnosisID", "diagnoses", "DiagnosisID"),

    ("encounter_procedures", "EncounterID", "encounters", "EncounterID"),
    ("encounter_procedures", "ProcedureID", "procedures", "ProcedureID"),

    ("admissions", "EncounterID", "encounters", "EncounterID"),
    ("admissions", "PatientID", "patients", "PatientID"),
    ("admissions", "DepartmentID", "departments", "DepartmentID"),

    ("appointments", "PatientID", "patients", "PatientID"),
    ("appointments", "ProviderID", "providers", "ProviderID"),
    ("appointments", "DepartmentID", "departments", "DepartmentID"),

    ("lab_results", "EncounterID", "encounters", "EncounterID"),
    ("lab_results", "PatientID", "patients", "PatientID")
]

In [48]:
ri_results = []

for child_table, child_fk, parent_table, parent_pk in relationship_checks:

    child_df = datasets[child_table]
    parent_df = datasets[parent_table]

    non_null_child = child_df[
        child_df[child_fk].notna()
    ]

    invalid_mask = (
        ~non_null_child[child_fk]
        .isin(parent_df[parent_pk])
    )

    invalid_count = invalid_mask.sum()

    ri_results.append({
        "ChildTable": child_table,
        "ForeignKey": child_fk,
        "ParentTable": parent_table,
        "ParentKey": parent_pk,
        "CheckedRows": len(non_null_child),
        "InvalidReferenceCount": invalid_count,
        "InvalidReferencePercent": round(
            invalid_count / len(non_null_child) * 100,
            3
        ) if len(non_null_child) > 0 else 0
    })

ri_profile_df = pd.DataFrame(ri_results)

ri_profile_df

,ChildTable,ForeignKey,ParentTable,ParentKey,CheckedRows,InvalidReferenceCount,InvalidReferencePercent
0,providers,DepartmentID,departments,DepartmentID,120,0,0.000
1,encounters,PatientID,patients,PatientID,90000,176,0.196
2,encounters,ProviderID,providers,ProviderID,88599,0,0.000
3,encounters,DepartmentID,departments,DepartmentID,90000,270,0.300
4,encounters,PayerID,payers,PayerID,90000,0,0.000
5,encounter_diagnoses,EncounterID,encounters,EncounterID,153595,0,0.000
6,encounter_diagnoses,DiagnosisID,diagnoses,DiagnosisID,153595,459,0.299
7,encounter_procedures,EncounterID,encounters,EncounterID,70419,0,0.000
8,encounter_procedures,ProcedureID,procedures,ProcedureID,70419,140,0.199
9,admissions,EncounterID,encounters,EncounterID,17740,0,0.000
10,admissions,PatientID,patients,PatientID,17740,35,0.197
11,admissions,DepartmentID,departments,DepartmentID,17740,0,0.000
12,appointments,PatientID,patients,PatientID,50000,107,0.214
13,appointments,ProviderID,providers,ProviderID,49600,0,0.000
14,appointments,DepartmentID,departments,DepartmentID,50000,0,0.000
15,lab_results,EncounterID,encounters,EncounterID,100000,0,0.000
16,lab_results,PatientID,patients,PatientID,100000,218,0.218

In [49]:
ri_issues_df = ri_profile_df[
    ri_profile_df[
        "InvalidReferenceCount"
    ] > 0
].sort_values(
    "InvalidReferenceCount",
    ascending=False
)

ri_issues_df

,ChildTable,ForeignKey,ParentTable,ParentKey,CheckedRows,InvalidReferenceCount,InvalidReferencePercent
6,encounter_diagnoses,DiagnosisID,diagnoses,DiagnosisID,153595,459,0.299
3,encounters,DepartmentID,departments,DepartmentID,90000,270,0.300
16,lab_results,PatientID,patients,PatientID,100000,218,0.218
1,encounters,PatientID,patients,PatientID,90000,176,0.196
8,encounter_procedures,ProcedureID,procedures,ProcedureID,70419,140,0.199
12,appointments,PatientID,patients,PatientID,50000,107,0.214
10,admissions,PatientID,patients,PatientID,17740,35,0.197

In [50]:
invalid_encounter_departments = encounters[
    encounters["DepartmentID"].notna()
    &
    ~encounters["DepartmentID"].isin(
        departments["DepartmentID"]
    )
]

invalid_encounter_departments.head()

,EncounterID,PatientID,ProviderID,DepartmentID,PayerID,EncounterDate,EncounterType,ArrivalDateTime,TriageDateTime,ProviderStartDateTime,EncounterEndDateTime,EncounterStatus,EncounterCost
32,ENC000033,PAT001397,PRV120,DEP999,PAY03,08-04-2025,Primary Care,08-04-2025 15:32,NaN,08-04-2025 15:38,03:07.9,Completed,173.33
565,ENC000566,PAT001937,PRV062,DEP999,PAY01,26-12-2025,Specialist,26-12-2025 11:05,NaN,26-12-2025 11:55,51:31.0,Completed,240.30
761,ENC000762,PAT004768,PRV016,DEP999,PAY04,12-04-2025,Specialist,12-04-2025 16:41,NaN,12-04-2025 16:59,58:26.7,Completed,768.68
1685,ENC001686,PAT002254,PRV024,DEP999,PAY01,13-12-2023,Specialist,13-12-2023 11:51,NaN,13-12-2023 11:54,37:04.8,Completed,815.40
1956,ENC001957,PAT001211,PRV008,DEP999,PAY02,19-10-2024,Outpatient,19-10-2024 13:39,NaN,19-10-2024 14:04,09:59.0,Completed,597.91

In [51]:
invalid_encounter_departments[
    "DepartmentID"
].value_counts()

DepartmentID
DEP999    270
Name: count, dtype: int64

In [52]:
invalid_diagnosis_refs = encounter_diagnoses[
    ~encounter_diagnoses[
        "DiagnosisID"
    ].isin(
        diagnoses["DiagnosisID"]
    )
]

invalid_diagnosis_refs.head()

,EncounterDiagnosisID,EncounterID,DiagnosisID,DiagnosisType,PresentOnAdmissionFlag
224,EDX0000225,ENC000133,DX999,Primary,NaN
711,EDX0000712,ENC000414,DX999,Secondary,0.0
762,EDX0000763,ENC000442,DX999,Primary,1.0
1344,EDX0001345,ENC000779,DX999,Primary,1.0
1424,EDX0001425,ENC000820,DX999,Secondary,NaN

In [53]:
invalid_diagnosis_refs[
    "DiagnosisID"
].value_counts()

DiagnosisID
DX999    459
Name: count, dtype: int64

In [54]:
invalid_procedure_refs = encounter_procedures[
    ~encounter_procedures[
        "ProcedureID"
    ].isin(
        procedures["ProcedureID"]
    )
]

invalid_procedure_refs.head()

     EncounterProcedureID EncounterID ProcedureID ProcedureDate  ProcedureCost
162            EPR0000163   ENC000207     PROC999    2025-11-17          69.97
1131           EPR0001132   ENC001415     PROC999    2025-02-11          87.02
1332           EPR0001333   ENC001676     PROC999    2024-07-04         240.71
1918           EPR0001919   ENC002408     PROC999    2024-08-06          87.64
2373           EPR0002374   ENC002989     PROC999    2023-02-08          90.66

In [55]:
lab_patient_check = (
    lab_results
    .merge(
        encounters[
            [
                "EncounterID",
                "PatientID"
            ]
        ],
        on="EncounterID",
        how="left",
        suffixes=(
            "_Lab",
            "_Encounter"
        )
    )
)

lab_patient_mismatches = lab_patient_check[
    lab_patient_check[
        "PatientID_Lab"
    ]
    !=
    lab_patient_check[
        "PatientID_Encounter"
    ]
]

print(
    "Lab / Encounter Patient mismatches:",
    len(lab_patient_mismatches)
)

Lab / Encounter Patient mismatches: 0

In [56]:
admission_patient_check = (
    admissions
    .merge(
        encounters[
            [
                "EncounterID",
                "PatientID"
            ]
        ],
        on="EncounterID",
        how="left",
        suffixes=(
            "_Admission",
            "_Encounter"
        )
    )
)

admission_patient_mismatches = (
    admission_patient_check[
        admission_patient_check[
            "PatientID_Admission"
        ]
        !=
        admission_patient_check[
            "PatientID_Encounter"
        ]
    ]
)

print(
    "Admission / Encounter Patient mismatches:",
    len(admission_patient_mismatches)
)

Admission / Encounter Patient mismatches: 0

In [57]:
appointment_provider_check = (
    appointments[
        appointments["ProviderID"].notna()
    ]
    .merge(
        providers[
            [
                "ProviderID",
                "DepartmentID"
            ]
        ],
        on="ProviderID",
        how="left",
        suffixes=(
            "_Appointment",
            "_Provider"
        )
    )
)

appointment_provider_department_mismatches = (
    appointment_provider_check[
        appointment_provider_check[
            "DepartmentID_Appointment"
        ]
        !=
        appointment_provider_check[
            "DepartmentID_Provider"
        ]
    ]
)

print(
    "Appointment provider/department mismatches:",
    len(
        appointment_provider_department_mismatches
    )
)

Appointment provider/department mismatches: 0

In [58]:
ri_profile_df.to_csv(
    PROFILING_PATH
    / "referential_integrity_profile.csv",
    index=False
)

print(
    "Referential integrity profile saved."
)

Referential integrity profile saved.

In [59]:
business_rule_results = []

def add_quality_result(
    rule_id,
    table,
    rule,
    issue_count,
    severity
):
    business_rule_results.append({
        "RuleID": rule_id,
        "Table": table,
        "Rule": rule,
        "IssueCount": int(issue_count),
        "Severity": severity
    })

In [60]:
business_rule_results = []

def add_quality_result(
    rule_id,
    table,
    rule,
    issue_count,
    severity
):
    business_rule_results.append({
        "RuleID": rule_id,
        "Table": table,
        "Rule": rule,
        "IssueCount": int(issue_count),
        "Severity": severity
    })

In [62]:
patients_check = patients.copy()

patients_check["BirthDate_dt"] = pd.to_datetime(
    patients_check["BirthDate"],
    errors="coerce"
)

patients_check["RegistrationDate_dt"] = pd.to_datetime(
    patients_check["RegistrationDate"],
    errors="coerce"
)

C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\3875870821.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  patients_check["BirthDate_dt"] = pd.to_datetime(

In [63]:
study_end_date = pd.Timestamp("2025-12-31")

future_birth_count = (
    patients_check["BirthDate_dt"]
    > study_end_date
).sum()

print(
    "Future BirthDates:",
    future_birth_count
)

Future BirthDates: 10

In [64]:
add_quality_result(
    "PAT-003",
    "patients",
    "BirthDate must not be after study end date",
    future_birth_count,
    "High"
)

In [65]:
birth_after_registration_count = (
    patients_check["BirthDate_dt"]
    >
    patients_check["RegistrationDate_dt"]
).sum()

print(
    "BirthDate after RegistrationDate:",
    birth_after_registration_count
)

BirthDate after RegistrationDate: 29

In [66]:
add_quality_result(
    "PAT-004",
    "patients",
    "BirthDate must be before RegistrationDate",
    birth_after_registration_count,
    "High"
)

In [67]:
valid_genders = [
    "Male",
    "Female",
    "Other",
    "Unknown"
]

invalid_gender_count = (
    ~patients["Gender"].isin(
        valid_genders
    )
).sum()

print(
    "Invalid Gender values:",
    invalid_gender_count
)

Invalid Gender values: 50

In [68]:
add_quality_result(
    "PAT-005",
    "patients",
    "Gender must use approved categories",
    invalid_gender_count,
    "Medium"
)

In [69]:
encounters_check = encounters.copy()

datetime_columns = [
    "ArrivalDateTime",
    "TriageDateTime",
    "ProviderStartDateTime",
    "EncounterEndDateTime"
]

for column in datetime_columns:
    encounters_check[column] = pd.to_datetime(
        encounters_check[column],
        errors="coerce"
    )

C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\1141053901.py:11: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  encounters_check[column] = pd.to_datetime(
C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\1141053901.py:11: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  encounters_check[column] = pd.to_datetime(
C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\1141053901.py:11: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  encounters_check[column] = pd.to_datetime(
C:\Users\Aakash\AppData\Local\Temp\ipykernel_34288\1141053901.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  encounters_check[column] = pd.to_datetime(

In [70]:
negative_encounter_cost_count = (
    encounters["EncounterCost"] < 0
).sum()

print(
    "Negative EncounterCost:",
    negative_encounter_cost_count
)

Negative EncounterCost: 180

In [71]:
add_quality_result(
    "ENC-008",
    "encounters",
    "EncounterCost must be non-negative",
    negative_encounter_cost_count,
    "High"
)

In [72]:
valid_encounter_types = [
    "Emergency",
    "Inpatient",
    "Outpatient",
    "Urgent Care",
    "Primary Care",
    "Specialist"
]

invalid_encounter_type_count = (
    ~encounters["EncounterType"].isin(
        valid_encounter_types
    )
).sum()

print(
    "Invalid EncounterType values:",
    invalid_encounter_type_count
)

Invalid EncounterType values: 450

In [73]:
add_quality_result(
    "ENC-006",
    "encounters",
    "EncounterType must use approved categories",
    invalid_encounter_type_count,
    "Medium"
)

In [74]:
provider_before_arrival_count = (
    encounters_check["ProviderStartDateTime"].notna()
    &
    (
        encounters_check["ProviderStartDateTime"]
        <
        encounters_check["ArrivalDateTime"]
    )
).sum()

print(
    "ProviderStart before Arrival:",
    provider_before_arrival_count
)

ProviderStart before Arrival: 450

In [75]:
add_quality_result(
    "ENC-010",
    "encounters",
    "ProviderStartDateTime must not precede ArrivalDateTime",
    provider_before_arrival_count,
    "High"
)

In [76]:
end_before_arrival_count = (
    encounters_check["EncounterEndDateTime"]
    <
    encounters_check["ArrivalDateTime"]
).sum()

print(
    "EncounterEnd before Arrival:",
    end_before_arrival_count
)

EncounterEnd before Arrival: 0

In [77]:
add_quality_result(
    "ENC-011",
    "encounters",
    "EncounterEndDateTime must not precede ArrivalDateTime",
    end_before_arrival_count,
    "Critical"
)

In [78]:
completed_missing_provider_count = (
    (
        encounters["EncounterStatus"] == "Completed"
    )
    &
    (
        encounters["ProviderID"].isna()
    )
).sum()

print(
    "Completed encounters missing ProviderID:",
    completed_missing_provider_count
)

Completed encounters missing ProviderID: 900

In [79]:
add_quality_result(
    "ENC-012",
    "encounters",
    "Completed encounters should have ProviderID",
    completed_missing_provider_count,
    "High"
)

In [80]:
negative_procedure_cost_count = (
    encounter_procedures[
        "ProcedureCost"
    ] < 0
).sum()

print(
    "Negative ProcedureCost:",
    negative_procedure_cost_count
)

Negative ProcedureCost: 140

In [81]:
add_quality_result(
    "EPR-006",
    "encounter_procedures",
    "ProcedureCost must be non-negative",
    negative_procedure_cost_count,
    "High"
)

In [82]:
admissions_check = admissions.copy()

for column in [
    "AdmissionDateTime",
    "DischargeDateTime",
    "FollowUpDate"
]:
    admissions_check[column] = pd.to_datetime(
        admissions_check[column],
        errors="coerce"
    )

In [83]:
discharge_before_admission_count = (
    admissions_check["DischargeDateTime"].notna()
    &
    (
        admissions_check["DischargeDateTime"]
        <
        admissions_check["AdmissionDateTime"]
    )
).sum()

print(
    "Discharge before Admission:",
    discharge_before_admission_count
)

Discharge before Admission: 53

In [84]:
add_quality_result(
    "ADM-008",
    "admissions",
    "DischargeDateTime must not precede AdmissionDateTime",
    discharge_before_admission_count,
    "Critical"
)

In [85]:
completed_followup_missing_date_count = (
    (
        admissions["FollowUpCompletedFlag"] == 1
    )
    &
    (
        admissions["FollowUpDate"].isna()
    )
).sum()

print(
    "Completed follow-up missing date:",
    completed_followup_missing_date_count
)

Completed follow-up missing date: 88

In [86]:
add_quality_result(
    "ADM-014",
    "admissions",
    "Completed follow-up must have FollowUpDate",
    completed_followup_missing_date_count,
    "High"
)

In [87]:
completed_without_required_count = (
    (
        admissions["FollowUpCompletedFlag"] == 1
    )
    &
    (
        admissions["FollowUpRequiredFlag"] == 0
    )
).sum()

print(
    "Follow-up completed when not required:",
    completed_without_required_count
)

Follow-up completed when not required: 0

In [88]:
add_quality_result(
    "ADM-013",
    "admissions",
    "FollowUpCompletedFlag should be consistent with FollowUpRequiredFlag",
    completed_without_required_count,
    "Medium"
)

In [89]:
valid_appointment_statuses = [
    "Completed",
    "Cancelled",
    "No Show",
    "Rescheduled"
]

In [90]:
invalid_appointment_status_count = (
    ~appointments[
        "AppointmentStatus"
    ].isin(
        valid_appointment_statuses
    )
).sum()

print(
    "Invalid AppointmentStatus:",
    invalid_appointment_status_count
)

Invalid AppointmentStatus: 150

In [91]:
add_quality_result(
    "APT-006",
    "appointments",
    "AppointmentStatus must use approved categories",
    invalid_appointment_status_count,
    "Medium"
)

In [92]:
appointments_check = appointments.copy()

appointments_check["ScheduledDate_dt"] = pd.to_datetime(
    appointments_check["ScheduledDate"],
    errors="coerce"
)

appointments_check["AppointmentDateTime_dt"] = pd.to_datetime(
    appointments_check["AppointmentDateTime"],
    errors="coerce"
)

In [93]:
appointment_before_schedule_count = (
    appointments_check[
        "AppointmentDateTime_dt"
    ].dt.normalize()
    <
    appointments_check[
        "ScheduledDate_dt"
    ].dt.normalize()
).sum()

print(
    "Appointment before ScheduledDate:",
    appointment_before_schedule_count
)

Appointment before ScheduledDate: 200

In [94]:
add_quality_result(
    "APT-008",
    "appointments",
    "AppointmentDateTime must not precede ScheduledDate",
    appointment_before_schedule_count,
    "High"
)

In [95]:
cancelled_missing_reason_count = (
    (
        appointments[
            "AppointmentStatus"
        ] == "Cancelled"
    )
    &
    (
        appointments[
            "CancellationReason"
        ].isna()
    )
).sum()

print(
    "Cancelled appointments missing reason:",
    cancelled_missing_reason_count
)

Cancelled appointments missing reason: 0

In [96]:
add_quality_result(
    "APT-010",
    "appointments",
    "Cancelled appointments should have CancellationReason",
    cancelled_missing_reason_count,
    "Medium"
)

In [97]:
expected_lab_units = {
    "HbA1c": "%",
    "Glucose": "mg/dL",
    "LDL Cholesterol": "mg/dL",
    "Creatinine": "mg/dL",
    "Hemoglobin": "g/dL"
}

In [98]:
lab_expected_unit = lab_results[
    "LabTest"
].map(
    expected_lab_units
)

invalid_lab_unit_count = (
    lab_results["ResultUnit"].notna()
    &
    (
        lab_results["ResultUnit"]
        != lab_expected_unit
    )
).sum()

print(
    "Incorrect lab units:",
    invalid_lab_unit_count
)

Incorrect lab units: 300

In [99]:
missing_lab_unit_count = (
    lab_results[
        "ResultUnit"
    ].isna().sum()
)

print(
    "Missing lab units:",
    missing_lab_unit_count
)

Missing lab units: 700

In [100]:
add_quality_result(
    "LAB-007",
    "lab_results",
    "ResultUnit must match expected unit for LabTest",
    invalid_lab_unit_count,
    "High"
)

add_quality_result(
    "LAB-006",
    "lab_results",
    "ResultUnit should not be missing",
    missing_lab_unit_count,
    "High"
)

In [101]:
invalid_reference_range_count = (
    lab_results["ReferenceLow"]
    >
    lab_results["ReferenceHigh"]
).sum()

print(
    "ReferenceLow > ReferenceHigh:",
    invalid_reference_range_count
)

ReferenceLow > ReferenceHigh: 200

In [102]:
add_quality_result(
    "LAB-009",
    "lab_results",
    "ReferenceLow must not exceed ReferenceHigh",
    invalid_reference_range_count,
    "High"
)

In [103]:
lab_outlier_records = []

for lab_test, group in lab_results.groupby(
    "LabTest"
):

    q1 = group[
        "ResultValue"
    ].quantile(0.25)

    q3 = group[
        "ResultValue"
    ].quantile(0.75)

    iqr = q3 - q1

    lower_bound = q1 - 3 * iqr
    upper_bound = q3 + 3 * iqr

    outlier_count = (
        (
            group["ResultValue"]
            < lower_bound
        )
        |
        (
            group["ResultValue"]
            > upper_bound
        )
    ).sum()

    lab_outlier_records.append({
        "LabTest": lab_test,
        "LowerBound": round(
            lower_bound,
            2
        ),
        "UpperBound": round(
            upper_bound,
            2
        ),
        "ExtremeOutlierCount": int(
            outlier_count
        )
    })

lab_outlier_profile_df = pd.DataFrame(
    lab_outlier_records
)

lab_outlier_profile_df

           LabTest  LowerBound  UpperBound  ExtremeOutlierCount
0       Creatinine       -0.43        2.44                   58
1          Glucose      -37.10      248.29                   59
2            HbA1c        0.05       12.37                   63
3       Hemoglobin        5.67       22.75                   59
4  LDL Cholesterol      -49.23      280.10                   61

In [104]:
business_rule_profile_df = pd.DataFrame(
    business_rule_results
)

business_rule_profile_df

,RuleID,Table,Rule,IssueCount,Severity
0,PAT-003,patients,BirthDate must not be after study end date,10,High
1,PAT-004,patients,BirthDate must be before RegistrationDate,29,High
2,PAT-005,patients,Gender must use approved categories,50,Medium
3,ENC-008,encounters,EncounterCost must be non-negative,180,High
4,ENC-006,encounters,EncounterType must use approved categories,450,Medium
5,ENC-010,encounters,ProviderStartDateTime must not precede Arrival...,450,High
6,ENC-011,encounters,EncounterEndDateTime must not precede ArrivalD...,0,Critical
7,ENC-012,encounters,Completed encounters should have ProviderID,900,High
8,EPR-006,encounter_procedures,ProcedureCost must be non-negative,140,High
9,ADM-008,admissions,DischargeDateTime must not precede AdmissionDa...,53,Critical
10,ADM-014,admissions,Completed follow-up must have FollowUpDate,88,High
11,ADM-013,admissions,FollowUpCompletedFlag should be consistent wit...,0,Medium
12,APT-006,appointments,AppointmentStatus must use approved categories,150,Medium
13,APT-008,appointments,AppointmentDateTime must not precede Scheduled...,200,High
14,APT-010,appointments,Cancelled appointments should have Cancellatio...,0,Medium
15,LAB-007,lab_results,ResultUnit must match expected unit for LabTest,300,High
16,LAB-006,lab_results,ResultUnit should not be missing,700,High
17,LAB-009,lab_results,ReferenceLow must not exceed ReferenceHigh,200,High

In [105]:
severity_order = {
    "Critical": 1,
    "High": 2,
    "Medium": 3,
    "Low": 4
}

business_rule_profile_df[
    "SeverityOrder"
] = business_rule_profile_df[
    "Severity"
].map(
    severity_order
)

business_rule_profile_df = (
    business_rule_profile_df
    .sort_values(
        [
            "SeverityOrder",
            "IssueCount"
        ],
        ascending=[
            True,
            False
        ]
    )
    .drop(
        columns="SeverityOrder"
    )
    .reset_index(
        drop=True
    )
)

business_rule_profile_df

,RuleID,Table,Rule,IssueCount,Severity
0,ADM-008,admissions,DischargeDateTime must not precede AdmissionDa...,53,Critical
1,ENC-011,encounters,EncounterEndDateTime must not precede ArrivalD...,0,Critical
2,ENC-012,encounters,Completed encounters should have ProviderID,900,High
3,LAB-006,lab_results,ResultUnit should not be missing,700,High
4,ENC-010,encounters,ProviderStartDateTime must not precede Arrival...,450,High
5,LAB-007,lab_results,ResultUnit must match expected unit for LabTest,300,High
6,APT-008,appointments,AppointmentDateTime must not precede Scheduled...,200,High
7,LAB-009,lab_results,ReferenceLow must not exceed ReferenceHigh,200,High
8,ENC-008,encounters,EncounterCost must be non-negative,180,High
9,EPR-006,encounter_procedures,ProcedureCost must be non-negative,140,High
10,ADM-014,admissions,Completed follow-up must have FollowUpDate,88,High
11,PAT-004,patients,BirthDate must be before RegistrationDate,29,High
12,PAT-003,patients,BirthDate must not be after study end date,10,High
13,ENC-006,encounters,EncounterType must use approved categories,450,Medium
14,APT-006,appointments,AppointmentStatus must use approved categories,150,Medium
15,PAT-005,patients,Gender must use approved categories,50,Medium
16,ADM-013,admissions,FollowUpCompletedFlag should be consistent wit...,0,Medium
17,APT-010,appointments,Cancelled appointments should have Cancellatio...,0,Medium

In [106]:
failed_business_rules_df = (
    business_rule_profile_df[
        business_rule_profile_df[
            "IssueCount"
        ] > 0
    ]
)

failed_business_rules_df

,RuleID,Table,Rule,IssueCount,Severity
0,ADM-008,admissions,DischargeDateTime must not precede AdmissionDa...,53,Critical
2,ENC-012,encounters,Completed encounters should have ProviderID,900,High
3,LAB-006,lab_results,ResultUnit should not be missing,700,High
4,ENC-010,encounters,ProviderStartDateTime must not precede Arrival...,450,High
5,LAB-007,lab_results,ResultUnit must match expected unit for LabTest,300,High
6,APT-008,appointments,AppointmentDateTime must not precede Scheduled...,200,High
7,LAB-009,lab_results,ReferenceLow must not exceed ReferenceHigh,200,High
8,ENC-008,encounters,EncounterCost must be non-negative,180,High
9,EPR-006,encounter_procedures,ProcedureCost must be non-negative,140,High
10,ADM-014,admissions,Completed follow-up must have FollowUpDate,88,High
11,PAT-004,patients,BirthDate must be before RegistrationDate,29,High
12,PAT-003,patients,BirthDate must not be after study end date,10,High
13,ENC-006,encounters,EncounterType must use approved categories,450,Medium
14,APT-006,appointments,AppointmentStatus must use approved categories,150,Medium
15,PAT-005,patients,Gender must use approved categories,50,Medium

In [107]:
business_rule_profile_df.to_csv(
    PROFILING_PATH
    / "business_rule_profile.csv",
    index=False
)

lab_outlier_profile_df.to_csv(
    PROFILING_PATH
    / "lab_outlier_profile.csv",
    index=False
)

print(
    "Business rule profiling outputs saved."
)

Business rule profiling outputs saved.

In [108]:
dq_issue_records = []

In [109]:
dq_issue_records.append({
    "IssueID": "DQ-001",
    "Table": "patients",
    "Field": "PatientID",
    "Issue": "Duplicate PatientID values",
    "IssueCount": int(
        patients["PatientID"].duplicated().sum()
    ),
    "Severity": "Critical",
    "BusinessImpact": (
        "Duplicate patient identifiers can cause double-counting, "
        "incorrect patient-level aggregation, and unreliable joins."
    ),
    "RecommendedRemediation": (
        "Investigate duplicate identifiers, retain one canonical "
        "patient record, and quarantine unresolved conflicts."
    )
})

In [110]:
dq_issue_records.append({
    "IssueID": "DQ-003",
    "Table": "patients",
    "Field": "Gender",
    "Issue": "Non-standard Gender categories",
    "IssueCount": int(
        (~patients["Gender"].isin(
            ["Male", "Female", "Other", "Unknown"]
        )).sum()
    ),
    "Severity": "Medium",
    "BusinessImpact": (
        "Inconsistent categories fragment demographic reporting "
        "and create duplicate dashboard groups."
    ),
    "RecommendedRemediation": (
        "Standardize known variations to approved categories."
    )
})

In [111]:
dq_issue_records.append({
    "IssueID": "DQ-004",
    "Table": "patients",
    "Field": "BirthDate",
    "Issue": "BirthDate after study period",
    "IssueCount": int(future_birth_count),
    "Severity": "High",
    "BusinessImpact": (
        "Invalid birth dates produce incorrect age and age-group "
        "calculations used in population analysis."
    ),
    "RecommendedRemediation": (
        "Flag impossible dates and exclude them from age-derived "
        "calculations until corrected."
    )
})

In [112]:
dq_issue_records.append({
    "IssueID": "DQ-005",
    "Table": "encounters",
    "Field": "DepartmentID",
    "Issue": "Invalid DepartmentID foreign keys",
    "IssueCount": int(
        len(invalid_encounter_departments)
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Affected encounters cannot be reliably attributed to "
        "departments or facilities."
    ),
    "RecommendedRemediation": (
        "Map valid department identifiers where recoverable; "
        "otherwise assign an Unknown/Unmapped department key."
    )
})

In [113]:
dq_issue_records.append({
    "IssueID": "DQ-006",
    "Table": "encounters",
    "Field": "EncounterCost",
    "Issue": "Negative encounter cost",
    "IssueCount": int(
        negative_encounter_cost_count
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Negative costs can understate total and average cost KPIs."
    ),
    "RecommendedRemediation": (
        "Flag invalid negative values and exclude them from financial "
        "KPIs unless a verified adjustment/credit meaning exists."
    )
})

In [114]:
dq_issue_records.append({
    "IssueID": "DQ-007",
    "Table": "encounters",
    "Field": "EncounterType",
    "Issue": "Non-standard EncounterType values",
    "IssueCount": int(
        invalid_encounter_type_count
    ),
    "Severity": "Medium",
    "BusinessImpact": (
        "Inconsistent encounter categories fragment utilization "
        "metrics across dashboards."
    ),
    "RecommendedRemediation": (
        "Map known variants such as ER, emergency, and Out Patient "
        "to approved encounter categories."
    )
})

In [115]:
dq_issue_records.append({
    "IssueID": "DQ-008",
    "Table": "encounters",
    "Field": "ProviderStartDateTime",
    "Issue": "ProviderStartDateTime precedes ArrivalDateTime",
    "IssueCount": int(
        provider_before_arrival_count
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Produces negative wait times and invalid operational "
        "performance metrics."
    ),
    "RecommendedRemediation": (
        "Flag invalid timestamp sequences and exclude those records "
        "from wait-time KPI calculations until corrected."
    )
})

In [116]:
dq_issue_records.append({
    "IssueID": "DQ-009",
    "Table": "encounters",
    "Field": "ProviderID",
    "Issue": "Completed encounter missing ProviderID",
    "IssueCount": int(
        completed_missing_provider_count
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Provider-level productivity and utilization metrics "
        "may be understated."
    ),
    "RecommendedRemediation": (
        "Retain null only where operationally valid; otherwise "
        "assign Unknown Provider for reporting."
    )
})

In [117]:
dq_issue_records.append({
    "IssueID": "DQ-010",
    "Table": "encounter_diagnoses",
    "Field": "DiagnosisID",
    "Issue": "Invalid DiagnosisID foreign keys",
    "IssueCount": int(
        len(invalid_diagnosis_refs)
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Diagnosis-level prevalence and utilization reporting "
        "may be incomplete."
    ),
    "RecommendedRemediation": (
        "Map valid codes where possible; otherwise classify as "
        "Unknown/Unmapped Diagnosis."
    )
})

In [118]:
dq_issue_records.append({
    "IssueID": "DQ-011",
    "Table": "encounter_diagnoses",
    "Field": "EncounterID + DiagnosisID",
    "Issue": "Duplicate encounter-diagnosis business keys",
    "IssueCount": int(
        encounter_diagnoses.duplicated(
            subset=["EncounterID", "DiagnosisID"]
        ).sum()
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Duplicate diagnoses can overstate diagnosis counts, "
        "condition prevalence, and diagnosis-level utilization."
    ),
    "RecommendedRemediation": (
        "Deduplicate identical encounter-diagnosis assignments "
        "after validating diagnosis type consistency."
    )
})

In [119]:
dq_issue_records.append({
    "IssueID": "DQ-012",
    "Table": "encounter_procedures",
    "Field": "ProcedureID",
    "Issue": "Invalid ProcedureID foreign keys",
    "IssueCount": int(
        len(invalid_procedure_refs)
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Procedure utilization and cost reporting may be incomplete."
    ),
    "RecommendedRemediation": (
        "Map valid procedure identifiers where possible or assign "
        "Unknown/Unmapped Procedure."
    )
})

In [120]:
dq_issue_records.append({
    "IssueID": "DQ-013",
    "Table": "encounter_procedures",
    "Field": "ProcedureCost",
    "Issue": "Negative ProcedureCost",
    "IssueCount": int(
        negative_procedure_cost_count
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Negative procedure costs distort service-line and "
        "procedure-level cost analysis."
    ),
    "RecommendedRemediation": (
        "Flag and exclude invalid negative values from cost KPIs "
        "unless verified as legitimate adjustments."
    )
})

In [122]:
dq_issue_records.append({
    "IssueID": "DQ-014",
    "Table": "admissions",
    "Field": "DischargeDateTime",
    "Issue": "Discharge occurs before admission",
    "IssueCount": int(
        discharge_before_admission_count
    ),
    "Severity": "Critical",
    "BusinessImpact": (
        "Creates negative length of stay and invalid inpatient "
        "performance metrics."
    ),
    "RecommendedRemediation": (
        "Flag and quarantine invalid date sequences before "
        "calculating LOS."
    )
})

In [123]:
dq_issue_records.append({
    "IssueID": "DQ-015",
    "Table": "admissions",
    "Field": "FollowUpDate",
    "Issue": "Completed follow-up missing FollowUpDate",
    "IssueCount": int(
        completed_followup_missing_date_count
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Prevents reliable measurement of follow-up timing "
        "and post-discharge care."
    ),
    "RecommendedRemediation": (
        "Flag inconsistent records and exclude them from "
        "time-to-follow-up calculations."
    )
})

In [124]:
dq_issue_records.append({
    "IssueID": "DQ-016",
    "Table": "appointments",
    "Field": "AppointmentStatus",
    "Issue": "Invalid AppointmentStatus values",
    "IssueCount": int(
        invalid_appointment_status_count
    ),
    "Severity": "Medium",
    "BusinessImpact": (
        "Invalid status categories distort no-show, completion, "
        "cancellation, and rescheduling KPIs."
    ),
    "RecommendedRemediation": (
        "Standardize known variants to approved appointment statuses."
    )
})

In [125]:
dq_issue_records.append({
    "IssueID": "DQ-017",
    "Table": "appointments",
    "Field": "AppointmentDateTime",
    "Issue": "Appointment occurs before ScheduledDate",
    "IssueCount": int(
        appointment_before_schedule_count
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Produces negative booking lead time and invalid "
        "scheduling-efficiency analysis."
    ),
    "RecommendedRemediation": (
        "Flag invalid records and exclude them from booking-lead "
        "time calculations."
    )
})

In [126]:
dq_issue_records.append({
    "IssueID": "DQ-018",
    "Table": "appointments",
    "Field": "ProviderID",
    "Issue": "Missing ProviderID",
    "IssueCount": int(
        appointments["ProviderID"].isna().sum()
    ),
    "Severity": "Medium",
    "BusinessImpact": (
        "Provider-level scheduling and capacity analysis "
        "may be incomplete."
    ),
    "RecommendedRemediation": (
        "Assign Unknown Provider where unresolved while preserving "
        "the appointment for department-level reporting."
    )
})

In [127]:
dq_issue_records.append({
    "IssueID": "DQ-019",
    "Table": "lab_results",
    "Field": "ResultUnit",
    "Issue": "Missing ResultUnit",
    "IssueCount": int(
        missing_lab_unit_count
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Numeric lab results without units may be ambiguous "
        "and unreliable for analytical interpretation."
    ),
    "RecommendedRemediation": (
        "Derive the expected unit from LabTest where the mapping "
        "is deterministic."
    )
})

In [128]:
dq_issue_records.append({
    "IssueID": "DQ-020",
    "Table": "lab_results",
    "Field": "ResultUnit",
    "Issue": "Incorrect ResultUnit for LabTest",
    "IssueCount": int(
        invalid_lab_unit_count
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Incorrect units can lead to invalid comparisons and "
        "misclassification of laboratory results."
    ),
    "RecommendedRemediation": (
        "Standardize ResultUnit using the approved LabTest-to-unit map."
    )
})

In [129]:
dq_issue_records.append({
    "IssueID": "DQ-021",
    "Table": "lab_results",
    "Field": "ReferenceLow / ReferenceHigh",
    "Issue": "ReferenceLow exceeds ReferenceHigh",
    "IssueCount": int(
        invalid_reference_range_count
    ),
    "Severity": "High",
    "BusinessImpact": (
        "Invalid reference ranges can produce incorrect abnormal-result "
        "classification."
    ),
    "RecommendedRemediation": (
        "Replace invalid ranges using approved reference values "
        "for each synthetic lab test."
    )
})

In [130]:
dq_issue_register_df = pd.DataFrame(
    dq_issue_records
)

dq_issue_register_df

,IssueID,Table,Field,Issue,IssueCount,Severity,BusinessImpact,RecommendedRemediation
0,DQ-001,patients,PatientID,Duplicate PatientID values,20,Critical,Duplicate patient identifiers can cause double...,"Investigate duplicate identifiers, retain one ..."
1,DQ-003,patients,Gender,Non-standard Gender categories,50,Medium,Inconsistent categories fragment demographic r...,Standardize known variations to approved categ...
2,DQ-004,patients,BirthDate,BirthDate after study period,10,High,Invalid birth dates produce incorrect age and ...,Flag impossible dates and exclude them from ag...
3,DQ-005,encounters,DepartmentID,Invalid DepartmentID foreign keys,270,High,Affected encounters cannot be reliably attribu...,Map valid department identifiers where recover...
4,DQ-006,encounters,EncounterCost,Negative encounter cost,180,High,Negative costs can understate total and averag...,Flag invalid negative values and exclude them ...
5,DQ-007,encounters,EncounterType,Non-standard EncounterType values,450,Medium,Inconsistent encounter categories fragment uti...,"Map known variants such as ER, emergency, and ..."
6,DQ-008,encounters,ProviderStartDateTime,ProviderStartDateTime precedes ArrivalDateTime,450,High,Produces negative wait times and invalid opera...,Flag invalid timestamp sequences and exclude t...
7,DQ-009,encounters,ProviderID,Completed encounter missing ProviderID,900,High,Provider-level productivity and utilization me...,Retain null only where operationally valid; ot...
8,DQ-010,encounter_diagnoses,DiagnosisID,Invalid DiagnosisID foreign keys,459,High,Diagnosis-level prevalence and utilization rep...,Map valid codes where possible; otherwise clas...
9,DQ-011,encounter_diagnoses,EncounterID + DiagnosisID,Duplicate encounter-diagnosis business keys,459,High,Duplicate diagnoses can overstate diagnosis co...,Deduplicate identical encounter-diagnosis assi...
10,DQ-012,encounter_procedures,ProcedureID,Invalid ProcedureID foreign keys,140,High,Procedure utilization and cost reporting may b...,Map valid procedure identifiers where possible...
11,DQ-013,encounter_procedures,ProcedureCost,Negative ProcedureCost,140,High,Negative procedure costs distort service-line ...,Flag and exclude invalid negative values from ...
12,DQ-014,admissions,DischargeDateTime,Discharge occurs before admission,53,Critical,Creates negative length of stay and invalid in...,Flag and quarantine invalid date sequences bef...
13,DQ-015,admissions,FollowUpDate,Completed follow-up missing FollowUpDate,88,High,Prevents reliable measurement of follow-up tim...,Flag inconsistent records and exclude them fro...
14,DQ-016,appointments,AppointmentStatus,Invalid AppointmentStatus values,150,Medium,"Invalid status categories distort no-show, com...",Standardize known variants to approved appoint...
15,DQ-017,appointments,AppointmentDateTime,Appointment occurs before ScheduledDate,200,High,Produces negative booking lead time and invali...,Flag invalid records and exclude them from boo...
16,DQ-018,appointments,ProviderID,Missing ProviderID,400,Medium,Provider-level scheduling and capacity analysi...,Assign Unknown Provider where unresolved while...
17,DQ-019,lab_results,ResultUnit,Missing ResultUnit,700,High,Numeric lab results without units may be ambig...,Derive the expected unit from LabTest where th...
18,DQ-020,lab_results,ResultUnit,Incorrect ResultUnit for LabTest,300,High,Incorrect units can lead to invalid comparison...,Standardize ResultUnit using the approved LabT...
19,DQ-021,lab_results,ReferenceLow / ReferenceHigh,ReferenceLow exceeds ReferenceHigh,200,High,Invalid reference ranges can produce incorrect...,Replace invalid ranges using approved referenc...

In [131]:
table_row_counts = {
    table_name: len(df)
    for table_name, df in datasets.items()
}

dq_issue_register_df[
    "TableRows"
] = dq_issue_register_df[
    "Table"
].map(
    table_row_counts
)

In [132]:
dq_issue_register_df[
    "IssuePercent"
] = (
    dq_issue_register_df[
        "IssueCount"
    ]
    /
    dq_issue_register_df[
        "TableRows"
    ]
    * 100
).round(3)

In [133]:
dq_issue_register_df = dq_issue_register_df[
    [
        "IssueID",
        "Table",
        "Field",
        "Issue",
        "IssueCount",
        "IssuePercent",
        "Severity",
        "BusinessImpact",
        "RecommendedRemediation"
    ]
]

In [134]:
dq_issue_register_df

,IssueID,Table,Field,Issue,IssueCount,IssuePercent,Severity,BusinessImpact,RecommendedRemediation
0,DQ-001,patients,PatientID,Duplicate PatientID values,20,0.200,Critical,Duplicate patient identifiers can cause double...,"Investigate duplicate identifiers, retain one ..."
1,DQ-003,patients,Gender,Non-standard Gender categories,50,0.500,Medium,Inconsistent categories fragment demographic r...,Standardize known variations to approved categ...
2,DQ-004,patients,BirthDate,BirthDate after study period,10,0.100,High,Invalid birth dates produce incorrect age and ...,Flag impossible dates and exclude them from ag...
3,DQ-005,encounters,DepartmentID,Invalid DepartmentID foreign keys,270,0.300,High,Affected encounters cannot be reliably attribu...,Map valid department identifiers where recover...
4,DQ-006,encounters,EncounterCost,Negative encounter cost,180,0.200,High,Negative costs can understate total and averag...,Flag invalid negative values and exclude them ...
5,DQ-007,encounters,EncounterType,Non-standard EncounterType values,450,0.500,Medium,Inconsistent encounter categories fragment uti...,"Map known variants such as ER, emergency, and ..."
6,DQ-008,encounters,ProviderStartDateTime,ProviderStartDateTime precedes ArrivalDateTime,450,0.500,High,Produces negative wait times and invalid opera...,Flag invalid timestamp sequences and exclude t...
7,DQ-009,encounters,ProviderID,Completed encounter missing ProviderID,900,1.000,High,Provider-level productivity and utilization me...,Retain null only where operationally valid; ot...
8,DQ-010,encounter_diagnoses,DiagnosisID,Invalid DiagnosisID foreign keys,459,0.299,High,Diagnosis-level prevalence and utilization rep...,Map valid codes where possible; otherwise clas...
9,DQ-011,encounter_diagnoses,EncounterID + DiagnosisID,Duplicate encounter-diagnosis business keys,459,0.299,High,Duplicate diagnoses can overstate diagnosis co...,Deduplicate identical encounter-diagnosis assi...
10,DQ-012,encounter_procedures,ProcedureID,Invalid ProcedureID foreign keys,140,0.199,High,Procedure utilization and cost reporting may b...,Map valid procedure identifiers where possible...
11,DQ-013,encounter_procedures,ProcedureCost,Negative ProcedureCost,140,0.199,High,Negative procedure costs distort service-line ...,Flag and exclude invalid negative values from ...
12,DQ-014,admissions,DischargeDateTime,Discharge occurs before admission,53,0.299,Critical,Creates negative length of stay and invalid in...,Flag and quarantine invalid date sequences bef...
13,DQ-015,admissions,FollowUpDate,Completed follow-up missing FollowUpDate,88,0.496,High,Prevents reliable measurement of follow-up tim...,Flag inconsistent records and exclude them fro...
14,DQ-016,appointments,AppointmentStatus,Invalid AppointmentStatus values,150,0.300,Medium,"Invalid status categories distort no-show, com...",Standardize known variants to approved appoint...
15,DQ-017,appointments,AppointmentDateTime,Appointment occurs before ScheduledDate,200,0.400,High,Produces negative booking lead time and invali...,Flag invalid records and exclude them from boo...
16,DQ-018,appointments,ProviderID,Missing ProviderID,400,0.800,Medium,Provider-level scheduling and capacity analysi...,Assign Unknown Provider where unresolved while...
17,DQ-019,lab_results,ResultUnit,Missing ResultUnit,700,0.700,High,Numeric lab results without units may be ambig...,Derive the expected unit from LabTest where th...
18,DQ-020,lab_results,ResultUnit,Incorrect ResultUnit for LabTest,300,0.300,High,Incorrect units can lead to invalid comparison...,Standardize ResultUnit using the approved LabT...
19,DQ-021,lab_results,ReferenceLow / ReferenceHigh,ReferenceLow exceeds ReferenceHigh,200,0.200,High,Invalid reference ranges can produce incorrect...,Replace invalid ranges using approved referenc...

In [135]:
dq_failed_issues_df = (
    dq_issue_register_df[
        dq_issue_register_df[
            "IssueCount"
        ] > 0
    ]
    .copy()
)

In [136]:
dq_failed_issues_df

,IssueID,Table,Field,Issue,IssueCount,IssuePercent,Severity,BusinessImpact,RecommendedRemediation
0,DQ-001,patients,PatientID,Duplicate PatientID values,20,0.200,Critical,Duplicate patient identifiers can cause double...,"Investigate duplicate identifiers, retain one ..."
1,DQ-003,patients,Gender,Non-standard Gender categories,50,0.500,Medium,Inconsistent categories fragment demographic r...,Standardize known variations to approved categ...
2,DQ-004,patients,BirthDate,BirthDate after study period,10,0.100,High,Invalid birth dates produce incorrect age and ...,Flag impossible dates and exclude them from ag...
3,DQ-005,encounters,DepartmentID,Invalid DepartmentID foreign keys,270,0.300,High,Affected encounters cannot be reliably attribu...,Map valid department identifiers where recover...
4,DQ-006,encounters,EncounterCost,Negative encounter cost,180,0.200,High,Negative costs can understate total and averag...,Flag invalid negative values and exclude them ...
5,DQ-007,encounters,EncounterType,Non-standard EncounterType values,450,0.500,Medium,Inconsistent encounter categories fragment uti...,"Map known variants such as ER, emergency, and ..."
6,DQ-008,encounters,ProviderStartDateTime,ProviderStartDateTime precedes ArrivalDateTime,450,0.500,High,Produces negative wait times and invalid opera...,Flag invalid timestamp sequences and exclude t...
7,DQ-009,encounters,ProviderID,Completed encounter missing ProviderID,900,1.000,High,Provider-level productivity and utilization me...,Retain null only where operationally valid; ot...
8,DQ-010,encounter_diagnoses,DiagnosisID,Invalid DiagnosisID foreign keys,459,0.299,High,Diagnosis-level prevalence and utilization rep...,Map valid codes where possible; otherwise clas...
9,DQ-011,encounter_diagnoses,EncounterID + DiagnosisID,Duplicate encounter-diagnosis business keys,459,0.299,High,Duplicate diagnoses can overstate diagnosis co...,Deduplicate identical encounter-diagnosis assi...
10,DQ-012,encounter_procedures,ProcedureID,Invalid ProcedureID foreign keys,140,0.199,High,Procedure utilization and cost reporting may b...,Map valid procedure identifiers where possible...
11,DQ-013,encounter_procedures,ProcedureCost,Negative ProcedureCost,140,0.199,High,Negative procedure costs distort service-line ...,Flag and exclude invalid negative values from ...
12,DQ-014,admissions,DischargeDateTime,Discharge occurs before admission,53,0.299,Critical,Creates negative length of stay and invalid in...,Flag and quarantine invalid date sequences bef...
13,DQ-015,admissions,FollowUpDate,Completed follow-up missing FollowUpDate,88,0.496,High,Prevents reliable measurement of follow-up tim...,Flag inconsistent records and exclude them fro...
14,DQ-016,appointments,AppointmentStatus,Invalid AppointmentStatus values,150,0.300,Medium,"Invalid status categories distort no-show, com...",Standardize known variants to approved appoint...
15,DQ-017,appointments,AppointmentDateTime,Appointment occurs before ScheduledDate,200,0.400,High,Produces negative booking lead time and invali...,Flag invalid records and exclude them from boo...
16,DQ-018,appointments,ProviderID,Missing ProviderID,400,0.800,Medium,Provider-level scheduling and capacity analysi...,Assign Unknown Provider where unresolved while...
17,DQ-019,lab_results,ResultUnit,Missing ResultUnit,700,0.700,High,Numeric lab results without units may be ambig...,Derive the expected unit from LabTest where th...
18,DQ-020,lab_results,ResultUnit,Incorrect ResultUnit for LabTest,300,0.300,High,Incorrect units can lead to invalid comparison...,Standardize ResultUnit using the approved LabT...
19,DQ-021,lab_results,ReferenceLow / ReferenceHigh,ReferenceLow exceeds ReferenceHigh,200,0.200,High,Invalid reference ranges can produce incorrect...,Replace invalid ranges using approved referenc...

In [137]:
severity_rank = {
    "Critical": 1,
    "High": 2,
    "Medium": 3,
    "Low": 4
}

dq_failed_issues_df[
    "_SeverityRank"
] = dq_failed_issues_df[
    "Severity"
].map(
    severity_rank
)

dq_failed_issues_df = (
    dq_failed_issues_df
    .sort_values(
        [
            "_SeverityRank",
            "IssueCount"
        ],
        ascending=[
            True,
            False
        ]
    )
    .drop(
        columns="_SeverityRank"
    )
    .reset_index(
        drop=True
    )
)

dq_failed_issues_df

,IssueID,Table,Field,Issue,IssueCount,IssuePercent,Severity,BusinessImpact,RecommendedRemediation
0,DQ-014,admissions,DischargeDateTime,Discharge occurs before admission,53,0.299,Critical,Creates negative length of stay and invalid in...,Flag and quarantine invalid date sequences bef...
1,DQ-001,patients,PatientID,Duplicate PatientID values,20,0.200,Critical,Duplicate patient identifiers can cause double...,"Investigate duplicate identifiers, retain one ..."
2,DQ-009,encounters,ProviderID,Completed encounter missing ProviderID,900,1.000,High,Provider-level productivity and utilization me...,Retain null only where operationally valid; ot...
3,DQ-019,lab_results,ResultUnit,Missing ResultUnit,700,0.700,High,Numeric lab results without units may be ambig...,Derive the expected unit from LabTest where th...
4,DQ-010,encounter_diagnoses,DiagnosisID,Invalid DiagnosisID foreign keys,459,0.299,High,Diagnosis-level prevalence and utilization rep...,Map valid codes where possible; otherwise clas...
5,DQ-011,encounter_diagnoses,EncounterID + DiagnosisID,Duplicate encounter-diagnosis business keys,459,0.299,High,Duplicate diagnoses can overstate diagnosis co...,Deduplicate identical encounter-diagnosis assi...
6,DQ-008,encounters,ProviderStartDateTime,ProviderStartDateTime precedes ArrivalDateTime,450,0.500,High,Produces negative wait times and invalid opera...,Flag invalid timestamp sequences and exclude t...
7,DQ-020,lab_results,ResultUnit,Incorrect ResultUnit for LabTest,300,0.300,High,Incorrect units can lead to invalid comparison...,Standardize ResultUnit using the approved LabT...
8,DQ-005,encounters,DepartmentID,Invalid DepartmentID foreign keys,270,0.300,High,Affected encounters cannot be reliably attribu...,Map valid department identifiers where recover...
9,DQ-017,appointments,AppointmentDateTime,Appointment occurs before ScheduledDate,200,0.400,High,Produces negative booking lead time and invali...,Flag invalid records and exclude them from boo...
10,DQ-021,lab_results,ReferenceLow / ReferenceHigh,ReferenceLow exceeds ReferenceHigh,200,0.200,High,Invalid reference ranges can produce incorrect...,Replace invalid ranges using approved referenc...
11,DQ-006,encounters,EncounterCost,Negative encounter cost,180,0.200,High,Negative costs can understate total and averag...,Flag invalid negative values and exclude them ...
12,DQ-012,encounter_procedures,ProcedureID,Invalid ProcedureID foreign keys,140,0.199,High,Procedure utilization and cost reporting may b...,Map valid procedure identifiers where possible...
13,DQ-013,encounter_procedures,ProcedureCost,Negative ProcedureCost,140,0.199,High,Negative procedure costs distort service-line ...,Flag and exclude invalid negative values from ...
14,DQ-015,admissions,FollowUpDate,Completed follow-up missing FollowUpDate,88,0.496,High,Prevents reliable measurement of follow-up tim...,Flag inconsistent records and exclude them fro...
15,DQ-004,patients,BirthDate,BirthDate after study period,10,0.100,High,Invalid birth dates produce incorrect age and ...,Flag impossible dates and exclude them from ag...
16,DQ-007,encounters,EncounterType,Non-standard EncounterType values,450,0.500,Medium,Inconsistent encounter categories fragment uti...,"Map known variants such as ER, emergency, and ..."
17,DQ-018,appointments,ProviderID,Missing ProviderID,400,0.800,Medium,Provider-level scheduling and capacity analysi...,Assign Unknown Provider where unresolved while...
18,DQ-016,appointments,AppointmentStatus,Invalid AppointmentStatus values,150,0.300,Medium,"Invalid status categories distort no-show, com...",Standardize known variants to approved appoint...
19,DQ-003,patients,Gender,Non-standard Gender categories,50,0.500,Medium,Inconsistent categories fragment demographic r...,Standardize known variations to approved categ...

In [138]:
dq_severity_summary_df = (
    dq_failed_issues_df
    .groupby(
        "Severity"
    )
    .agg(
        NumberOfIssues=(
            "IssueID",
            "count"
        ),
        AffectedRecords=(
            "IssueCount",
            "sum"
        )
    )
    .reset_index()
)

dq_severity_summary_df

   Severity  NumberOfIssues  AffectedRecords
0  Critical               2               73
1      High              14             4496
2    Medium               4             1050

In [139]:
dq_table_summary_df = (
    dq_failed_issues_df
    .groupby(
        "Table"
    )
    .agg(
        QualityIssues=(
            "IssueID",
            "count"
        ),
        TotalIssueOccurrences=(
            "IssueCount",
            "sum"
        )
    )
    .reset_index()
    .sort_values(
        "TotalIssueOccurrences",
        ascending=False
    )
)

dq_table_summary_df

                  Table  QualityIssues  TotalIssueOccurrences
4            encounters              5                   2250
5           lab_results              3                   1200
2   encounter_diagnoses              2                    918
1          appointments              3                    750
3  encounter_procedures              2                    280
0            admissions              2                    141
6              patients              3                     80

In [140]:
dq_failed_issues_df.to_csv(
    PROFILING_PATH
    / "data_quality_issue_register.csv",
    index=False
)

dq_severity_summary_df.to_csv(
    PROFILING_PATH
    / "data_quality_severity_summary.csv",
    index=False
)

dq_table_summary_df.to_csv(
    PROFILING_PATH
    / "data_quality_table_summary.csv",
    index=False
)

print(
    "Consolidated Data Quality reports saved successfully."
)

Consolidated Data Quality reports saved successfully.

In [141]:
print("=" * 70)
print("RIVERCARE HEALTH SYSTEM - RAW DATA QUALITY ASSESSMENT")
print("=" * 70)

print(
    f"\nSource Tables Assessed: {len(datasets)}"
)

print(
    f"Total Raw Records: {sum(len(df) for df in datasets.values()):,}"
)

print(
    f"Failed Data Quality Rules: {len(dq_failed_issues_df)}"
)

print("\nSeverity Distribution:")
print(
    dq_failed_issues_df[
        "Severity"
    ].value_counts()
)

print("\nTop Data Quality Issues:")

print(
    dq_failed_issues_df[
        [
            "IssueID",
            "Table",
            "Issue",
            "IssueCount",
            "Severity"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

======================================================================
RIVERCARE HEALTH SYSTEM - RAW DATA QUALITY ASSESSMENT
======================================================================

Source Tables Assessed: 12
Total Raw Records: 491,995
Failed Data Quality Rules: 20

Severity Distribution:
Severity
High        14
Medium       4
Critical     2
Name: count, dtype: int64

Top Data Quality Issues:
IssueID               Table                                          Issue  IssueCount Severity
 DQ-014          admissions              Discharge occurs before admission          53 Critical
 DQ-001            patients                     Duplicate PatientID values          20 Critical
 DQ-009          encounters         Completed encounter missing ProviderID         900     High
 DQ-019         lab_results                             Missing ResultUnit         700     High
 DQ-010 encounter_diagnoses               Invalid DiagnosisID foreign keys         459     High
 DQ-011 encounter_diagnoses    Duplicate encounter-diagnosis business keys         459     High
 DQ-008          encounters ProviderStartDateTime precedes ArrivalDateTime         450     High
 DQ-020         lab_results               Incorrect ResultUnit for LabTest         300     High
 DQ-005          encounters              Invalid DepartmentID foreign keys         270     High
 DQ-017        appointments        Appointment occurs before ScheduledDate         200     High